### ISSUE TITLE
Grundlast in der Serverauslastung gesondert anzeigen

### ISSUE THREAD

**Issue by twiesing** [mittwald/feature-requests#105]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Aktuell ist die Auslastung der Server nicht genau nachvollziehbar.

**Welche Lösungsideen hast du?**
Die Grundlast durch z.B. die dedizierte Datenbank transparent mit anzeigen.

**Comment by patrickhilker** [comment]
Hier ein aktueller Einblick in die geplante Veränderung.

<img width="770" alt="image" src="https://github.com/user-attachments/assets/2fbd2f13-f651-430b-a1ff-b9bf0958e4b5">

**Comment by patrickhilker** [comment]
Die durch Datenbanken verursachte Auslastung ist nun sichtbar.

![Image](https://github.com/user-attachments/assets/6abeb161-7fb2-43ec-9bfe-ab0f00065c57)
