### ISSUE TITLE
App spezifische ENV Variablen

### ISSUE THREAD

**Issue by bugskarl** [mittwald/feature-requests#107]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Sehr viele Frameworks lassen sich mittels Environment Variablen konfigurieren um z.B. DB Credentials, API Keys, Environment Context, ... zu setzen. Das ist momentan nur über .htaccess (web only) oder z.B. symfony/dotenv (web + cli) möglich. Und um "geheime" Werte zu setzen muss das ganze über SSH/vim angelegt und angepasst werden. Eine Serverseitige Lösung fehlt jedenfalls derzeit.

**Welche Lösungsideen hast du?**
Pro App soll es möglich sein Environment Variablen anzulegen und anzupassen. Mit der Option ob diese "sicher" abgespeichert werden sollen, also der Wert über die Web-UI nach dem speichern nicht mehr ausgegben wird.

<img width="644" alt="env-variables" src="https://github.com/mittwald/feature-requests/assets/89250539/dbb1bba1-b37f-4c4c-a7c2-d95dcecf7b48">

_-- Beispiel: Variablen Verwaltung @ Bitbucket_

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Diese Variablen müssen auch bei Scheduler Tasks und SSH Verbindungen gesetzt sein.

**Comment by patrickhilker** [comment]
Tja, mit dem Feature-Vorschlag war ich schneller. 😎 Wir haben schon ein paar erste Überlegungen dazu angestellt, u.a. auch über automatisch bereitgestellte Umgebungsvariablen (z.B. für Datenbankzugangsdaten o.ä.). Gerne nehmen wir deinen Input noch zusätzlich dazu auf.

Duplikat von https://github.com/mittwald/feature-requests/issues/97
