### ISSUE TITLE
Domain verbinden, wenn man sie in der App auswählt

### ISSUE THREAD

**Issue by lmrkavogt** [mittwald/feature-requests#109]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Wenn ich eine neue App installiere (bspw. Nextcloud) und eine Doamin auswähle (bspw. cloud.test.de) wird diese Domain nicht automatisch mit der App verbunden, sondern bleibt im Zweifelsfall ohne Ziel.

**Welche Lösungsideen hast du?**
Die App automatisch mit der Domain verbinden, die ausgewählt wurde.

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Falls es hier begründete Einwände gibt: ggf. ein Auswahlfeld, mit dem man die Verbindung bestätigen muss. "Möchtest Du, dass diese App automatisch das Ziel der ausgewählten App wird?"

**Comment by patrickhilker** [comment]
Normalerweise sollte genau das, was du beschreibst, passieren... Wir prüfen. 😄

**Comment by patrickhilker** [comment]
Gefunden - da scheint sich ein eventual consistency-Problem eingeschlichen zu haben. Fixen wir morgen.

**Comment by lmrkavogt** [comment]
Hupsi 😅 Hatte mich schon gewundert, dass da nichts passiert und den Bug fast vermutet :D

Dankeee

**Comment by patrickhilker** [comment]
Der Fix wurde deployed.
