### ISSUE TITLE
Kopieren von Apps innerhalb eines Projekts

### ISSUE THREAD

**Issue by thueske** [mittwald/feature-requests#11]
**Bezieht sich dein Feature-Request auf ein zugrundeliegendes Problem? Bitte beschreibe es uns:**
Für Entwicklungszwecke möchte ich schnell und einfach eine zweite Instanz meiner App anlegen.

**Beschreibe die Lösung(en), die du dir vorstellen könntest:**
Kopierfunktion im mStudio, mit der ich mit wenigen Klicks eine App duplizieren kann.

**Comment by Rinxiao** [comment]
Für uns würde dieses Feature auch projektübergreifend innerhalb eines Space-Servers Sinn machen, da wir für verschiedene Projekte eigene "Kopiervorlagen" mit Basis-Einstellungen haben.
