### ISSUE TITLE
SSL-Zertifikat optional statt Fehlermeldung

### ISSUE THREAD

**Issue by rteitge** [mittwald/feature-requests#113]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Aktuell habe ich in diversen Projekten im Studio subdomains eingerichtet, die per A-Record auf andere Server zeigen, weil dort zB ein Docker Compose Projekt hinter traefik läuft. Im Studio bekomme ich dann die Meldung `Für diese Domain konnte kein SSL-Zertifikat ausgestellt werden, da die Domain per IP nicht auf deine Server-IP [...] zeigt.` - was ich in dem Fall auch nicht will, da der Zielserver für das SSL-Zertifikat verantwortlich ist.

**Welche Lösungsideen hast du?**
Entweder das Ausblenden und nicht mehr Anzeigen der Fehlermeldung und des Icons in der Domain Liste, oder ein Flag, das ich in der Subdomain manuell setzen muss, dass kein Zertifikat ausgestellt werden soll.

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
![grafik](https://github.com/mittwald/feature-requests/assets/83205200/7677c0a4-04cb-4ec7-9a41-90370d39190f)
![grafik](https://github.com/mittwald/feature-requests/assets/83205200/3fd96239-7890-4a6b-8a5e-32e87bc106bc)

**Comment by jotimann** [comment]
Hallo @rteitge,
du kannst den Banner nun über einen Link im Banner ausblenden und die Fehlermeldung ausblenden:

![Image](https://github.com/user-attachments/assets/74c95f33-a76b-4271-8fab-1a8c46502a47)

Wenn gewünscht kannst du die Ausstellung anschließend wieder in den Domain-Details starten:

![Image](https://github.com/user-attachments/assets/e1c5a7f1-d694-4705-8da2-808c94d3476c)

Gruß Jonas

**Comment by rteitge** [comment]
Hallo Jonas,

klasse! Vielen Dank dafür :-)

Beste Grüße
