### ISSUE TITLE
Rechnungsempfänger nicht aus Organisations-Kontakten wählbar

### ISSUE THREAD

**Issue by subnoodle** [mittwald/feature-requests#114]
Hallo Mittwälder,

ich vermisse eine Funktion:
Wenn ich den Email-Empfänger der Rechnungen auswählen / verändern möchte, muss ich einen ganz neuen Kontakt in einzlenen Feldern angeben, könnte dabei versehentlich auch den rechtlichen Rechnungsempfänger, was etwas komplett anderes ist, ändern.

Der Wunsch wäre, den E-Mail-Empfänger separat festlegen zu können; diesen frei angeben zu können oder wahlweise aus der Oranisations-Kontatliste zu wählen (Rolle Buchhaltung ist ja prädestiniert dafür: Meine Buchhalterin ist bereits als Mitglied meiner Organisation angelegt, aber sie hat keine Möglichkeit, eine eigene Mailadresse zu haben; ausserdem ist sie als Mitglieder meiner Orga nicht auswählbar).

Vielen Dank, Th. Wittich

PS: Hinweis: Ursprünglich war das ein Ticket aus dem mStudio (ID dort: ftcfvyss).

**Comment by alexakruse** [comment]
Hey!
Danke für das Feedback. Deine ursprüngliche Anfrage ist bei uns auch schon als Feature Request hinterlegt und wurde diskutiert.

> Der Wunsch wäre, den E-Mail-Empfänger separat festlegen zu können; ; diesen frei angeben zu können oder wahlweise aus der Oranisations-Kontatliste zu wählen   

würdest du dir hier wünschen, dass die E-Mail nur an die ausgewählte Mail geschickt wird, oder ergänzend? Dann würdest du als Vertragspartner die Rechnung bekommen, wie auch die angegebene E-Mail-Adresse oder ein ausgewählter User.

**Comment by alexakruse** [comment]
Wir haben lange hin und her überlegt wie wir es machen: 
Du kannst in deinen Zahlungsmodalitäten einen zusätzlichen Rechnungsempfänger hinzufügen. Die Rechnung geht also weiterhin an den eingetragenen Vertragspartner, kann darüber hinaus aber auch an eine weitere E-Mail-Adresse deiner Wahl verschickt werden. 
Wir haben uns im ersten Schritt bewusst dagegen entschieden, dass der Empfänger aus deiner Liste an Organisationsmitgliedern gewählt werden kann, weil wir noch einiges mehr hätten bedenken und implementieren müssen, um auch beim Ausscheiden eines Mitglieds immer auf dem aktuellen Stand zu sein. Wir gucken in den nächsten 2 Monaten, wie häufig das Feature genutzt wird, um dann die nächsten Schritte zu evaluieren!
