### ISSUE TITLE
DDEV-Integration

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/feature-requests#118]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Als Entwickler möchte ich schnell und einfach eine lokale Entwicklungsumgebung meines mStudio-Projekts starten.

**Welche Lösungsideen hast du?**
Nahtlose Integration mit [DDEV](https://ddev.com).

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Gewünschter Funktionsumfang:

- Einfaches Projekt-Setup
- Automatisierte Erstellung einer [DDEV-Projektkonfiguration](https://ddev.readthedocs.io/en/stable/users/configuration/config/), die zu dem entsprechenden mStudio-Projekt passt (PHP-Version, Datenbank, installierte Anwendung, ...)
- Nutzung der [mittwald CLI][cli] innerhalb des Web-Containers, inkl. Unterstützung für einen Aufruf über das Host-System mit `ddev mw ...`
- Unterstützung für `ddev pull`, um schnell eine lokale Entwicklungsumgebung aus einem bestehenden Projekt initialisieren und auf dem aktuellen Stand halten zu können
- (Optional) Unterstützung für `ddev push`, um lokale Entwicklungsdaten zurück auf das Projekt schieben zu können (auch wenn das natürlich keine "richtige" Deployment-Lösung ersetzt; vgl. hierzu eher https://github.com/mittwald/feature-requests/issues/52).

**Aktueller Arbeitsstand**

- [x] https://github.com/mittwald/cli/pull/173 fügt der [mittwald CLI][cli] die Option hinzu, das Dateisystem einer App-Installation auf den lokalen Arbeitsplatzrechner herunterladen zu können
- [x] https://github.com/mittwald/cli/pull/204 fügt der mittwald CLI die Option hinzu, einen Dump einer MySQL-Datenbank auf den lokalen Arbeitsplatzrechner herunterladen zu können
- [x] https://github.com/mittwald/cli/pull/220 fügt der mittwald CLI ein `mw ddev init`-Kommando hinzu, welches anhand der mStudio-Projektkonfiguration eine passende `.ddev/config.yaml`-Datei erstellt und auf dem aktuellen Stand hält
- [x] https://github.com/mittwald/ddev/pull/1 implementiert ein [DDEV-Addon](https://ddev.readthedocs.io/en/stable/users/extend/additional-services/) (installierbar mit `ddev get mittwald/ddev`), welches Unterstützung für die Befehle `ddev mw ...`, `ddev pull mittwald` und `ddev push mittwald` hinzufügt.
- [x] https://github.com/mittwald/cli/pull/243 Unterstützung für `mw app upload`- und `mw database mysql import`-Commands für `ddev push`-Unterstützung
- [x] https://github.com/mittwald/developer-portal/pull/83 Dokumentation üblicher Use Cases im Developer Portal

[cli]: https://github.com/mittwald/cli

**Comment by martin-helmich** [comment]
An alle Interessierten:

Es steht nun eine prototypische DDEV-Integration zum Test zur Verfügung, zu der mich euer Feedback interessieren würde. Die Integration besteht aus zwei Teilen:

1. einem Unterbefehl der [`mw`-CLI](https://github.com/mittwald/cli), um ein DDEV-Projekt aus einer bestehenden mittwald-App zu initialisieren (wer sie schon installiert hat: einmal vorher `mw update` ausführen).
2. ein [DDEV-Addon](https://github.com/mittwald/ddev), welches Unterstützung für die `ddev pull`- und `ddev push`-Befehle (letztes kommt erst noch) hinzufügt.

Die Dokumentation des Ganzen ist in https://github.com/mittwald/developer-portal/pull/83 vorbereitet; den aktuellen Arbeitsstand der Dokumentation könnt ihr beispielsweise [hier](https://github.com/mittwald/developer-portal/blob/feature/ddev/docs/technologies/development/ddev.md) einsehen (später natürlich im Developer Portal).

Lasst allgemeines Feedback gerne hier im Issue; Feedback zu spezifischen Punkten der Dokumentation auch gerne direkt in https://github.com/mittwald/developer-portal/pull/83.

**Comment by tehplague** [comment]
Es wäre sehr gut, wenn man den Pull auf einzelne Verzeichnisse beschränken könnte. Der rsync-Filter reicht da leider nicht, weil die heruntergeladenen Dateien dann im falschen Verzeichnis landen.
Hintergrund: Wir benutzen Deployer, haben also im App-Filesystem mehrere Releases inkl. der gesharten Dateien liegen. Nur die will ich aber eigentlich laden. D.h. ich möchte einen Teil der Dateien aus dem App-Filesystem haben und die aber an eine andere Stelle lokal schieben (quasi zwei Verzeichnisebenen darüber).

Ich bin ohnehin gerade dabei, den Prozess dafür aufzusetzen und kann euch daher gerne am konkreten Beispiel zeigen, was wir gerne machen würden, wenn euch das hilft.

**Comment by martin-helmich** [comment]
> Ich bin ohnehin gerade dabei, den Prozess dafür aufzusetzen und kann euch daher gerne am konkreten Beispiel zeigen, was wir gerne machen würden, wenn euch das hilft.

Hey @tehplague; 👋  den "Deployer und DDEV"-Usecase haben wir bisher tatsächlich noch nicht wirklich bedacht, und ich fände es in der Tat interessant, mal über euren konkreten Ansatz sprechen zu können. Darf ich mal über einen privaten Kanal (E-Mail, oder TYPO3-Slack, vielleicht) Kontakt aufnehmen?

**Comment by tehplague** [comment]
Hey @martin-helmich, gerne. Am besten über das TYPO3-Slack, da heiß ich einfach "cspoo".

**Comment by martin-helmich** [comment]
Ich schließe dieses Issue an dieser Stelle erstmal; der Support für die DDEV-Integration ist mittlerweile in `mw` enthalten (welches auch sein erstes stable Release bekommen hat), und alle Features sind dokumentiert. 🚀

Weiteres Feedback zur DDEV-Integration dann gerne direkt im [mittwald/cli](https://github.com/mittwald/cli)- oder [mittwald/ddev](https://github.com/mittwald/ddev)-Repository, zur Dokumentation gerne in [mittwald/developer-portal](https://github.com/mittwald/developer-portal).
