### ISSUE TITLE
Extension für Raycast

### ISSUE THREAD

**Issue by twiesing** [mittwald/feature-requests#120]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich möchte aus meiner gewohnten Umgebung heraus schnell auf Projekte im mStudio bzw. Kundencenter zugreifen.

**Welche Lösungsideen hast du?**
Es wäre super cool, wenn es eine Raycast-Extension gäbe, mit der ich z.B. Projekte und Domains suchen kann. Im ersten Schritt wäre es denkbar, dass bei Klick auf ein Ergebnis dieses im mStudio geöffnet wird. 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
- https://www.raycast.com/mblode/google-search
- https://www.raycast.com/shukantpal/digitalocean
- https://www.raycast.com/tonka3000/gitlab

**Comment by twiesing** [comment]
@danieldeichfuss hat da was gebaut: https://github.com/raycast/extensions/pull/14196

**Comment by danieldeichfuss** [comment]
🎉 Extension ist veröffentlicht https://www.raycast.com/danieldeichfuss/mittwald

Die kann jetzt Organisationen, Projekte, Domains, Apps und Endpunkte in der API Doku suchen. Gerne testen und Feedback geben.

**Comment by twiesing** [comment]
Coole Sache! Funktioniert 1a, danke für deine Umsetzung 👏🏻  Wir nehmen sie ins mStudio-Changelog auf.
