### ISSUE TITLE
Massenaktualisierungstools für PHP Updates

### ISSUE THREAD

**Issue by maikbehring** [mittwald/feature-requests#125]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich benötige eine effiziente Lösung für die Massenaktualisierung von PHP-Versionen bei Webseiten, die ähnliche Konfigurationen nutzen, ohne jede Seite einzeln bearbeiten zu müssen.

**Welche Lösungsideen hast du?**
Ein Tool zur Massenaktualisierung, das es ermöglicht, PHP-Versionen für alle Webseiten, die bestimmte Kriterien erfüllen (z.B. das gleiche CMS verwenden), mit einem Klick zu aktualisieren.

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**

**Comment by paul-hph** [comment]
Im Falle von WordPress und Typo3 müssen bei so etwas auf jeden Fall die installieren Plugins in die Kriterien mit einbezogen werden. Es braucht also eine Liste von Wordpress-Plugins und TYPO3 Erweiterungen und deren PHP-Kompatibilität. 

Bei selbst entwickelten Extensions müssten man anders vorgeben. (https://github.com/PHPCompatibility/PHPCompatibility)

**Comment by patrickhilker** [comment]
Wir haben die Kundencenter-API um einen Endpunkt erweitert, der ein Anheben der PHP-Version ermöglicht.

https://developer.mittwald.de/reference/v1/#tag/Software/operation/updatePhp
