### ISSUE TITLE
Support und Hilfestellung bei Update

### ISSUE THREAD

**Issue by The-Web-Designer** [mittwald/feature-requests#126]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Das Problem besteht darin, dass ich als Reseller hin und wieder Unterstützung beim Update auf neue PHP-Versionen oder auch bei Problemen mit PHP-Konvertierungen benötige,... Jeder kennt das, wenn es im Agenturalltag "brennt" und man "mal eben" eine kleine Hilfe bräuchte. Zum Beispiel wenn man sehr viele Webseiten in sehr kurzer Zeit umstellen muss, möchte oder sollte... ....

**Welche Lösungsideen hast du?**
Ein (kostenpflichtiges) Support-Team, das spezialisierte Hilfe oder Anpassungen vornimmt, oder Tools, die einem bei der Umstellung helfen, z.B. Dateiprüfung im Tool auf PHP 8.x Kompatibilität und ggf. inkl. Fehlerkorrektur, damit man die eigenen Ressourcen besser einsetzen kann... 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Screenshots habe ich keine, aber sowas gab es schon mal als "Magento Support Team" oder ich glaube auch für "Typo3" ....

**Comment by martin-helmich** [comment]
> Tools, die einem bei der Umstellung helfen, z.B. Dateiprüfung im Tool auf PHP 8.x Kompatibilität und ggf. inkl. Fehlerkorrektur, damit man die eigenen Ressourcen besser einsetzen kann...

Stichwort "Tools": Hier wäre [Rector](https://github.com/rectorphp/rector) womöglich eine Empfehlung; damit lassen sich PHP-Upgrades ab 5.3 aufwärts (zumindest teil-)automatisieren. Für TYPO3-Projekte gibt es ebenfalls [eine Rector-Distribution](https://github.com/sabbelasichon/typo3-rector). Falls Interesse daran besteht, bekämen wir sicherlich ein paar Dokumentationen oder Blog-Posts auf die Reihe.

**Comment by patrickhilker** [comment]
Ich schließe dieses Issue, da ich hier keinen akuten Handlungsbedarf aus Entwicklungssicht sehe. Die Idee als Dienstleistung habe ich an die entsprechende Stelle weitergegeben.
