### ISSUE TITLE
PHP Updateinformation - CSV im Kundencenter

### ISSUE THREAD

**Issue by The-Web-Designer** [mittwald/feature-requests#128]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
In dieser CSV sind auch Accounts enthalten, die bereits PHP 8.1 (oder höher) haben und somit keine zusätzlichen Kosten verursachen, schöner wäre es, wenn nur die Accounts enthalten wären, die auch ab dem 1. Mai zusätzliche Kosten verursachen, damit man die Liste auf 0 abarbeiten kann bzw. eine schönere Übersicht hat.

**Welche Lösungsideen hast du?**
Einfach die Konten aus der Liste entfernen, die keine zusätzlichen Kosten verursachen (ja, man kann auch mit Excel filtern), aber so wäre es von Anfang an übersichtlicher...

**Comment by sinareim** [comment]
@The-Web-Designer Hi Thomas, danke für dein Feedback. Die Anzahl der betroffenen Accounts ist in der Kachel auf dem Dashboard sichtbar. Ein Vorteil der aktuellen Darstellung in der csv besteht darin, auf einem Blick auch alle Projekte zu sehen, die nicht betroffen sind und der Anmerkungsspalte entnehmen zu können, wann der PHP Extended Support zukünftig starten wird. Ich bin gespannt, wie da der Tenor anderer Kunden ist. Ansonsten lässt sich das ganz bestimmt ändern 👍 :)

**Comment by CarstenHager** [comment]
Wäre es möglich, dass sich die Liste im Kundencenter automatisch (täglich) aktualisiert? Somit wäre man auch vorbereitet auf evtl. später anfallende Kosten.

**Comment by subnoodle** [comment]
Hi @sinareim, ich weiss jetzt nicht, welches Dashboard Du meinst. Finde so etwas nicht.
Aber unter Software -> nach Anwendung filtern -> php auswählen erhalten ich eine Liste MIT den Versionen von PHP dazu.
Diese Liste wäre super, wenn sie noch downloadbar wäre.
Ist das auch das, was @The-Web-Designer sucht?
Grüße, Thomas W.

**Comment by sinareim** [comment]
@subnoodle Die von mir erwähnte csv findest du im Kundencenter unter login.mittwald.de im Reiter "Projekte" ganz oben in einem Banner mit der Überschrift "Deine PHP Versionen". Dort findest du dann auch eine projektübergreifende Auflistung der gesamten Kundennummer und nicht nur auf den jeweiligen Server beschränkt.

Bei weiteren Fragen außerhalb von Featurewünschen nutze am besten das Ticketsystem. :)

Beste Grüße
Sina

**Comment by CarstenHager** [comment]
@sinareim in welchen Abständen wird die Liste aktualisiert?

**Comment by maikbehring** [comment]
Wille jetzt nicht lügen, aber meines Wissens wird sie on the fly generiert.

**Comment by patrickhilker** [comment]
> Wille jetzt nicht lügen, aber meines Wissens wird sie on the fly generiert.

Korrekt - die ist immer aktuell.

**Comment by patrickhilker** [comment]
Ich schätze hier den Mehrwert, alle Projekte zu sehen, als größer als die "Übersichtlichkeit", die leicht erreichbar ist, ein. Darum schließe ich das Issue.
