### ISSUE TITLE
Unsicherheit bezüglich des konkreten zeitlichen Ausblicks der Preissteigerung von 5 auf 15 Euro

### ISSUE THREAD

**Issue by The-Web-Designer** [mittwald/feature-requests#129]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Das Hauptproblem liegt in der Unsicherheit bezüglich des konkreten zeitlichen Ausblicks der Preissteigerung von 5 auf 15 Euro für Hosting-Accounts. Diese Unklarheit erschwert die finanzielle Planung und Kommunikation mit Endkunden.

**Welche Lösungsideen hast du?**
Es wird eine klare und verlässliche Ankündigung benötigt, die den Zeitpunkt der Preissteigerung für Hosting-Accounts von 5 auf 15 Euro definiert.

Grund ist das im Screenshot, die PHP Versionen < 5.6 erst ab Mai 2025  "Eingestellt" werden = 15€ kosten sollten, bei euch ist es aber schon der Mai 2024. 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
![Bildschirmfoto 2024-03-06 um 08 29 36](https://github.com/mittwald/feature-requests/assets/34239722/02ba49bd-6676-4ca0-a300-669e6114bcf0)

**Comment by sinareim** [comment]
Hi @The-Web-Designer, es ist absolut nachvollziehbar, dass du Planungssicherheit benötigst in der Kommunikation mit deinem Endkunden. Genau dafür ist die von dir angehängte Grafik auch gedacht. Ich nehme aber wahr, dass wir diese nochmal optimieren müssen ;). 

PHP-Versionen <5.6 werden ab dem 01.05.2024 mit 15 Euro monatlich berechnet. Sie werden im Mai 2025 abgeschaltet und stehen ab dann auch nicht mehr zur Verfügung. 

PHP 5.6 wird zwischen dem 01.05.2024 und August 2026 mit 5 Euro pro Monat kostenpflichtig über den PHP Extended Support. Ab August 2026 (frühestens, jedoch wahrscheinlich) wird dieser Artikel mit 15 Euro bepreist. Auch diese PHP-Version wird (mit genügend Vorlaufzeit) irgendwann abgeschaltet (ähnlich PHP-Versionen < 5.6 aktuell). Wir werden alle betroffenen Kunden mind. 6 Monate vorher informieren.

**Comment by patrickhilker** [comment]
Ich lese hier keinen konkreten Handlungsbedarf raus. Aus diesem Grund würde ich das Issue schließen. @The-Web-Designer, wenn du dir konkrete Handlungen wünscht, würde ich dich bitten, sie nochmal hier im Issue zu formulieren.
