### ISSUE TITLE
Versionsübersicht im mStudio

### ISSUE THREAD

**Issue by lmrkavogt** [mittwald/feature-requests#132]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich möchte mir meine installierten Softwareversionen per Klick im mStudio anzeigen lassen, diese nach Software, Version etc. filtern und als CSV exportieren.

**Welche Lösungsideen hast du?**
Integration einer Übersicht auf Server- oder Organisationsebene, die alle Softwareversionen anzeigt:
Server; Projekt; App; Software; Version

ggf. noch erweitert um die aktuellste, verfügbare Version

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Im ersten Schritt natürlich mit Priorität PHP ;)

**Comment by patrickhilker** [comment]
Wir haben für verschiedene Objekte (Domains, Apps, ...) projektübergreifende Übersichtslisten, möglicherweise inkl. Stapelverarbeitung, geplant. Das wird aber nicht kurzfristig umsetzbar sein.

Für den konkreten PHP-Fall hat unser Kollege @thueske einen kleinen Container zusammengebastelt: https://github.com/thueske/mstudio-php-viewer. Der listet bequem alle Apps und PHP-Versionen auf.

**Comment by patrickhilker** [comment]
Wir werden im mStudio im ersten Schritt eine App-Übersicht einführen, die alle Apps, auf die der eingeloggte User Zugriff hat, angezeigt werden. Zusätzlich reichern wir die Seite mit sinnvollen Details zu den Apps an.

**Comment by bugskarl** [comment]
hilfreich wäre hier ein status der anzeigt, falls eine unsichere version im einsatz ist. aktuell gerade der fall bei PHP: https://seclists.org/oss-sec/2024/q2/113

**Comment by patrickhilker** [comment]
> hilfreich wäre hier ein status der anzeigt, falls eine unsichere version im einsatz ist. aktuell gerade der fall bei PHP: https://seclists.org/oss-sec/2024/q2/113

Wir möchten in nächster Zukunft u. a. PHP-Versionen auf Patchlevel-Ebene automatisch aktuell halten. Ein Opt-Out ist dafür (im ersten Schritt) nicht vorgesehen, sodass alle Kunden jederzeit von aktuellen Versionen profitieren (insbesondere auch im Kontext von PHP Extended Support).

Bei relevanten Sicherheitslücken machen wir das allerdings auch schon heute.

**Comment by patrickhilker** [comment]
Es steht ab sofort eine Übersichtsseite, die alle Apps, auf die der angemeldete User Zugriff hat, auflistet. Dort werden auch App-Updates angeboten und die aktuell installierte PHP-Version angezeigt. Damit sollten die meisten Anwendungsfälle erschlagen sein. Falls euch noch etwas fehlt, erstellt gerne neue Issues. 😊
