### ISSUE TITLE
Push-Benachrichtigungen

### ISSUE THREAD

**Issue by lmrkavogt** [mittwald/feature-requests#133]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich möchte vom mStudio per Push benachrichtigt werden, wenn ich eine Benachrichtigung erhalte. So möchte ich verhindern, dass ggf. wichtige Benachrichtigungen untergehen.

**Welche Lösungsideen hast du?**
Integration einer Push-Funktion mit Einstellungsmöglichkeiten (auf Nutzer-Ebene), welche Benachrichtigungen wie übermittelt werden sollen, z.B. "App installiert" und Checkboxen "nur im mStudio", "per Mail", "per Push"

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Beispiel HumHub:
![image](https://github.com/mittwald/feature-requests/assets/142482043/ddcc0321-d394-4e13-91e4-9d07059a2d7f)

**Comment by patrickhilker** [comment]
Duplikat von https://github.com/mittwald/feature-requests/issues/103
