### ISSUE TITLE
Mehr Daten für die CSV im Kundencenter

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#134]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Als Agentur mit ca. 1500 Account, muss ich aufgrund des kostenpflichtigen PHP Supports dringend ausmisten, und zwar schnell!
Ungenutzte Accounts, Kopien, Dev Accounts, Test Accounts, Entwickler Spielwiesen.. 

Um besser einschätzen zu können, was wegkann, was aktualisiert werden kann, wäre es hilfreich, wenn die CSV im Kundencenter mehr Informationen bereitstellen könnte. 

**Welche Lösungsideen hast du?**

1. Sind in dem P-Account Email-Postfächer zugewiesen. 
2. Mit welchem Verzeichnis/Software sind die Domains verknüpft. (Was ist die tatsächlich aktive Software)
3. Sind in dem P-Account überhaupt Domains zugewiesen. 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**

Kandidaten für die manuelle Prüfung zur Deaktivierung/Löschung wären dann Projekte ohne Domain, ohne E-Mail-Postfächer mit alten PHP-Versionen. 

Wir haben leider auch viele Accounts, in denen tatsächlich noch inaktive Domains angelegt sind. 
Dafür habe ich mir allerdings eine Laravel App geschrieben, die mir alle Accounts und Domains von Mittwald per API holt, diese verknüpft, und anschließend per A-Record Lookup prüft, ob diese überhaupt auf den Mittwald Server zeigt. 
Falls ihr diese Information auch bereitstellen könntet, wäre das nice.

**Comment by patrickhilker** [comment]
Wir werden, nach aktuellem Stand, die CSV-Datei um die Anzahl der Domains, Anzahl Postfächer und Anzahl E-Mail-Adressen erweitern.

**Comment by patrickhilker** [comment]
Die Anzahl der Domains und Postfächer wird jetzt in der CSV-Datei mit ausgegeben.
