### ISSUE TITLE
PHP Extended Support - Entwickler P-Konten

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#135]
Wenn wir vermehrt in Zukunft unsere Projekte, die bereits mit einer PHP Extended Support Gebühr belegt sind, aktualisieren wollen, würden wir zunächst einmal eine Accountkopie anlegen. 

Ich gehe davon aus, dass diese Account Kopie ebenfalls mit einer PHP Extended Support Gebühr belegt wird, was für uns Zusatzkosten verursachen würde, die wir gerne vermeiden wollen.

Könntet Ihr eine Möglichkeit schaffen, ein Konto als Entwickler-Konto zu markieren und somit die Kosten zu vermeiden?
Von mir aus könnt ihr da auch Anforderungen stellen. z. B. keine aktive Domain oder ein aktiver Verzeichnisschutz.

**Comment by patrickhilker** [comment]
Nach aktuellem Stand wird die Abrechnung der kostenpflichtigen Versionen nach 7 Tagen starten – d. h. so lange ist es möglich, die alte PHP-Version kostenlos zu nutzen. Wird innerhalb dieser Zeit auf eine aktuelle PHP-Version aktualisiert, fallen keine Kosten an.

Hilft euch dieses Vorgehen? Oder gibt es Gründe, die dazu führen, dass ihr noch länger auf einer alten PHP-Version bleiben müsst?
