### ISSUE TITLE
RAM Auslastungsanzeige + DB Optimierung

### ISSUE THREAD

**Issue by The-Web-Designer** [mittwald/feature-requests#139]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Die RAM-Auslastung im mStudio zeigt nicht die Auslastung auf "Projektebene" an, sondern auch die "Grundlast", diese Grundlast sollte in einer anderen Farbe dargestellt werden, außerdem sollte es vielleicht ein "weiches Ende" des RAM geben, z.B. ich habe 8 GB reserviert, bekomme bei 95% eine Mail, dass ich das Paket anpassen muss, sonst kann es zu Fehlern wegen zu wenig RAM kommen und bei 8,8 GB geht es dann hart ab (und nicht schon bei 8).

**Welche Lösungsideen hast du?**
Idee zur besseren Darstellung der RAM-Auslastung, einer weichen Obergrenze und ggf. einer DB-Optimierung (die man im mStudio aktivieren/deaktivieren kann, um z.B. jede Nacht die DB automatisch optimieren zu lassen und so den RAM-Verbrauch minimieren zu können.

**Comment by lmrkavogt** [comment]
Ergänzend dazu mehr Infos über die Auslastung der Server, bspw.
- dein Server tritt in den Spitzen häufig über die gebuchte Leistung, bitte prüfe ein Tarifupgrade
- dein Projekt "XYZ" ist sehr leistungsintensiv, bitte prüfe eine Auslagerung auf proSpace
- wir haben festgestellt, dass deine DB nicht optimiert ist - du kannst hier eine automatische Optimierung aktivieren


Damit wird es für den mStudio-Anwender etwas "greifbarer", wie es um die eigenen Server steht.

**Comment by patrickhilker** [comment]
Den Wunsch, die Grundlast anders darzustellen, haben wir hier schon erfasst: https://github.com/mittwald/feature-requests/issues/105

Eine weiche Grenze ist nach meinem Verständnis für RAM nicht machbar – wenn voll, dann voll. Ein bisschen Gratis-RAM on top gibts daher schon. 😊 

Notifications zum Thema Auslastung wären aber definitiv denkbar ([und sind für Speicherplatz auch schon in Arbeit](https://github.com/mittwald/feature-requests/issues/14)). Soll ich das als neues Issue erstellen? Mag von euch jemand? 🚀

**Comment by The-Web-Designer** [comment]
Dann bräuchten wir 2 neue Themen

1. Notifications zum Thema Auslastung 
2. "Schalter" im mStudio zum Zeitlichen Optimieren der DB?!

**Comment by paul-hph** [comment]
`dein Projekt "XYZ" ist sehr leistungsintensiv, bitte prüfe eine Auslagerung auf proSpace`

👍 👍 Wenn es diese Anzeige pro App geben könnte, wäre das super.

Aktuell haben wir den Fall, dass einzelne Aktionen in Apps den RAM komplett belegen und den ganze Server und alle Applikationen lahmlegen (DB: OUT OF Memory). 
Laut MW wird hier bereits an einer Lösung gearbeitet, aber selbst wenn die gefunden ist, wäre dieses Feature hilfreich: 
Man wüsste, welche Projekte man optimieren oder ausgliedern müsste.

**Comment by patrickhilker** [comment]
> Dann bräuchten wir 2 neue Themen 

Jau, sehr gut 👍🏻 

> "Schalter" im mStudio zum Zeitlichen Optimieren der DB?!

Magst du das dann noch etwas ausführen? Ist damit mehr als ein `optimize` auf den einzelnen Tabellen gemeint?

**Comment by The-Web-Designer** [comment]
Magst du das dann noch etwas ausführen? Ist damit mehr als ein optimize auf den einzelnen Tabellen gemeint? 

--> Aktuell von meinem Wissenstand her nicht, aber vielleicht gibt es da noch was besseres? Ich dachte an ein einfaches optimize, was mir schon oft sehr viel Speicher "freigegeben" hat.. (gerade auf dem klassischen mServer) - aber da muss man es halt manuell anstoßen.. ;-/

**Comment by patrickhilker** [comment]
> Wenn es diese Anzeige pro App geben könnte, wäre das super.

Insbesondere bei der Datenbank haben wir das Problem, dass wir die nicht auf Projekt-Ebene runterbrechen können. Es läuft eine Datenbankinstanz für den gesamten Server. Darum sehe ich aktuell leider nicht, dass wir das sogar pro App ermitteln können.

**Comment by patrickhilker** [comment]
Ich habe hier ein Folge-Issue zum Thema "Notifications für RAM- und CPU-Auslastung" erstellt: https://github.com/mittwald/feature-requests/issues/150

@The-Web-Designer Ich würde dich bitten, für das "automatische OPTIMIZE" ein neues Issue zu erstellen.

**Comment by The-Web-Designer** [comment]
Dies ist hier zu finden: https://github.com/mittwald/feature-requests/issues/151
