### ISSUE TITLE
White Label E-Mail-Verwaltung

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#146]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Beispiel: Als Agentur möchte ich meinen Kunden ein White-Label-Login unter einer eigenen Domain geben.
(kundencenter.meineagentur.com)

**Welche Lösungsideen hast du?**
Ein White-Label Lösung für das mStudio zur Verfügung stellen.

**Comment by patrickhilker** [comment]
Hey @paul-hph, danke für den Vorschlag. Der kommt – du hast es dir vermutlich gedacht – wenig überraschend. :-)

Aus unserer Erfahrung wissen wir, dass es in der Regel um den E-Mail-Bereich, in manchen Fällen auch um DNS geht. Habt ihr da noch weitergehende Anforderungen?

**Comment by paul-hph** [comment]
Gerne erst mal mit den Emails starten. Freigabe Struktur gerne wie im Klassik Kundencenter.

**Comment by patrickhilker** [comment]
> Gerne erst mal mit den Emails starten.

Da haben wir was in petto - wir kommen auf dich zu.

**Comment by bugskarl** [comment]
wir bräuchten beim E-Mail-Administrator noch die möglichkeit die verwaltbaren domains einzuschränken. also ein admin soll die @eins.com und @zwei.com adressen anlegen/verwalten können und wiederum ein anderen die @drei.com adressen - im gleichen projekt.
daraus ergibt sich dann auch eine möglichkeit einem E-Mail-Administrator lediglich die adressen verwaltung für eine der domains freizugeben, bei uns gibt es nämlich durchaus viele redirect domains für welche keine email adresse angelegt werden kann/soll. weiters kann man dann die @abc.p-def.project.space herausfiltern bzw. diese eben nicht zur verwaltung für diese admins freigeben.

**Comment by patrickhilker** [comment]
Hallo @bugskarl, magst du ein paar Hintergrundinfos liefern, wie es zu so einer Anforderung kommt? Bisher ist unser Rechte-/Rollen-Konzept ja maximal auf das Projekt ausgerichtet, und müsste dafür nicht unerheblich erweitert werden.

Oder konkreter gefragt:

- Warum liegen die Domains zusammen in einem Projekt?
- Wodurch unterscheiden sich die User, die auf die einzelnen Domains zugreifen dürfen? Beispielsweise: unterschiedliche Firmen/Abteilungen, unterschiedliche Stellen/Positionen ..?

Möglicherweise haben wir eine alternative Lösung in der Hinterhand, dazu kommen wir ggf. gezielt auf dich zu.

**Comment by bugskarl** [comment]
ahoi @patrickhilker,

die domains liegen zusammen in einem projekt weil sie z.b. als weiterleitung dienen. bespiel: es gibt z.b. www.tierinfo.at aber auch tierinfo.ch und tierinfo.eu und tierportal.at und tierproblem.at, ... alles weiterleitungen auf www.tierinfo.at. ein E-Mail-Administrator hat hier die auswahl all dieser domains, wobei nur die hauptdomain korrekt aufgesetzt wird und nur diese sinn macht zur email anlage.

und auch den firmen/abteilugs use case haben wir. beispiel: es gibt ~1500 floristInen in oö, dazu kommen bezirks und stadtgärnereien. alle werden in einem neuen www.schooen.at zusammengefasst - durchwegs jedoch mit eigener domain aufgeschalten. jeder dieser user soll aber natürlich nur die eigenen email adressen verwalten/erstellen können.

und dann kommt noch das oben erwähnte filtern der @abc.p-def.project.space adressen dazu. für diese domain email adressen anzulegen macht keinen sinn und würde zur besseren gestaltung/verwaltung für den E-Mail-Administrator beitragen.

lg

**Comment by patrickhilker** [comment]
Ich versuche das mal für mich zusammenzufassen: Es geht um Multi-Domain-Instanzen (z. B. WordPress oder TYPO3), die nicht alle zum gleichen Kunden gehören?

**Comment by bugskarl** [comment]
@patrickhilker zum einen, ja. zum anderen könnte man durch die limitierung der domains pro E-Mail-Administrator der person das leben einfacher machen indem man die anzahl der möglichen mail endungen reduziert - die zusätzlichen domains ergeben sich z.b. aus weiterleitungen oder der project.space domains.

**Comment by patrickhilker** [comment]
Vielleicht habt ihr sie schon gesehen: Unser mStudio kann jetzt durch Extensions erweitert werden. Eine der ersten Extensions ist der "Postmaster", mit dem es möglich ist, eine Whitelabel E-Mail-Verwaltung für eure Kunden bereitzustellen.

Zum Ausprobieren, klickt euch einfach ins entsprechende Projekt, wählt im Menü "Extensions" aus, dort werdet ihr dann durch den Installationsprozess geleitet. Feedback zur Extension selbst bitte direkt an unseren Contributor, Feedback zum Installations-/Verwaltungsprozess im mStudio gerne an uns.
