### ISSUE TITLE
automatische OPTIMIZE der DB

### ISSUE THREAD

**Issue by The-Web-Designer** [mittwald/feature-requests#151]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Grundsatzthema hier: https://github.com/mittwald/feature-requests/issues/139
(DB-Optimierung (die man im mStudio aktivieren/deaktivieren kann, um z.B. jede Nacht die DB automatisch optimieren zu lassen und so den RAM-Verbrauch minimieren zu können.)

Es wäre schön, hätte man "Pro Server" / "Pro Projekt" einen Button zum automatischen OPTIMIZE der DB, verbunden mit einer Uhrzeit wann das aktiviert werden soll. -> Jetzt / in 4h / heute Nach um 2.00 Uhr / ....  

**Welche Lösungsideen hast du?**
So einfach wie Möglich :)

**Comment by patrickhilker** [comment]
Ich bin unsicher, ob das eine gute Idee ist. Das wird u. U. dazu führen, dass Datenbanken gelockt werden, d. h. nicht gelesen/beschrieben werden können, was zu Problemen innerhalb der Applikation führt. Außerdem ist OPTIMIZE meines Wissens nicht dafür gedacht, RAM freizugeben, sondern es wird Speicherplatz freigegeben (der in der Regel wohl kaum das Problem ist). Das aber auch nur in besonderen Fällen (z. B. NICHT bei InnoDB-Tabellen).

Ich halte dieses Feature darum nicht für sinnvoll. Gerne lasse ich mich umstimmen (mit entsprechenden Quellen), würde das Issue vorläufig aber schließen.

Quelle u. a.: https://dba.stackexchange.com/questions/129351/would-a-cron-job-to-automatically-optimize-tables-on-a-monthly-basis-be-ideal
