### ISSUE TITLE
Bei Projektkopie sollen Konfigurationen mit angepasst werden

### ISSUE THREAD

**Issue by dieseitenwerkstatt** [mittwald/feature-requests#152]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
: Bei einer Projektkopie einer App werden nur das Filesystem und die DBs in eine neue App kopiert. Die Konfiguration möglicher darin enthaltener CMS wird nicht angetastet. Da darauf auch nicht hingewiesen wird, ändert man im Glauben ind erneuen App zu arbeiten dann unweigerlich Inhalte der urspünglichen, oft auch der Live-App.

**Welche Lösungsideen hast du?**
### kurzfristig:
Bei der Kopie sollte auch die Konfiguration der jeweiligen App angepasst werden. Bei allen mir bekannten php-basierten CMS wären dazu nur die DB-Details in der config zu ändern, bei den anderen Apps wäre es sicherlich auch nicht mehr. Da alle Apps definierte Applikationen beinhalten (ausser die statische/custom app), sollte das ohne grossen Aufwand zu machen sein

### umgehend:
Bei einer Projektkopie sollte man sehr sichbar darauf hingewiesen werden, dass man manuell in der config eine Änderung nachziehen muss, bevor man mit der Arbeit beginnt oder das System an weitere Bearbeiter, Redakteure und Kunden weiterreicht.

**Comment by patrickhilker** [comment]
Hallo @dieseitenwerkstatt, eigentlich passiert genau das, was du beschreibst - wir passen die Datenbank-Konfiguration an. Wäre ja sonst total witzlos. 😄 

Das müssten wir uns wohl als Einzelfall genauer anschauen. Dafür ist es am einfachsten, wenn du ein Ticket für den Kundenservice erstellst (bezieh dich dann gerne auf dieses Issue, dann sollte es bei mir landen).

**Comment by martin-helmich** [comment]
Es gab ja auch schonmal die Überlegung, derartige Konfiguration zukünftig bevorzugt über Umgebungsvariablen vorzunehmen (vgl. #97, mit einem wohlberechtigten Verweis auf die [12-Factor-App](https://12factor.net/de/config)).

Das würde die Situation in diesem Fall ja etwas entspannen (und würde auch mit benutzerdefinierten Apps funktionieren, die nicht aktiv von mittwald gemanaged werden), weil in der Konfiguration der App dann einfach nur noch ein (obacht, ausgedachtes Beispiel) `getenv('DATABASE_PASSWORD')` stehen müsste (und im Falle einer Kopie auf einfach da stehen _bleiben_ könnte).

**Comment by dieseitenwerkstatt** [comment]
> Hallo @dieseitenwerkstatt, eigentlich passiert genau das, was du beschreibst - wir passen die Datenbank-Konfiguration an. Wäre ja sonst total witzlos. 😄
> 
> Das müssten wir uns wohl als Einzelfall genauer anschauen. Dafür ist es am einfachsten, wenn du ein Ticket für den Kundenservice erstellst (bezieh dich dann gerne auf dieses Issue, dann sollte es bei mir landen).

Hallo @patrickhilker 
Ja, ich hätte erwartet, dass die Konfiguration mit angepasst wird. Laut der Kollegin an der Hotline gestern, die mich bat, das Ganze auch hier zu melden, ist das Thema allerdings bei euch bekannt. Sie hat es selber an die Produktverbesserung gemeldet und es werden keine Konfigurationen angepasst, das Ganze befindet sich aktuell noch in Entwicklung.
Jetzt weiss ich leider nicht was stimmt. Fakt ist nur, dass egal ob ich innerhalb eines Projektes oder von einem Projekt in ein anderes eine App kopiere, die Datenbank und die Files dupliziert werden, die Konfiguration zeigt aber in allen Fällen auf die ursprüngliche App.

**Comment by patrickhilker** [comment]
Ich hab das gerade selbst nochmal getestet – die Zugangsdaten zur Datenbank werden wie erwartet ausgetauscht (zumindest in WordPress). Ich würde dich darum bitten, ein Support-Ticket zu erstellen, damit wir auf deinen individuellen Fall schauen können. Bezieh dich dabei gerne auf dieses Issue.

Gleichzeitig spiele ich dieses Issue als Feedback in den Kundenservice.

Das Issue schließe ich, da ich hier keinen konkreten Handlungsbedarf sehe. Das Feature ist ja grundsätzlich da. :-)
