### ISSUE TITLE
Kundencenter Bug: Projekt umbenennen

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#153]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Aktuell müssen wir Hunderte Accounts umbenennen/deaktivieren etc. #phpfun
Dabei hindert es enorm, dass bei jeden 3 Versuch, dass **Umbenennen der Accounts nicht funktioniert** und das Kundencenter ein offensichtlich kaputtes UI ausgibt ohne Hinweise, was das Problem ist. 
Ich habe seit letzter Woche versucht dies bereits über den Support beheben zu lassen, leider wird mit mir Suport-Ping-Pong gespielt. 
(Ich soll meinen Browser wechseln, ich soll versuchen eine andere Sprache einzustellen. Support kann das Problem nicht nachstellen)

**Welche Lösungsideen hast du?**
Bitte das Problem beheben. Wenn es an Zeichen oder Länge, gibt bitte einen Hinweis ausgeben. UI fixen. 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**

https://github.com/mittwald/feature-requests/assets/3603487/7275e83e-8f5c-4505-afaf-2b163758c9f6

**Comment by patrickhilker** [comment]
Hallo @paul-hph, das Problem ist die Zeichenlänge. Diese ist (schon immer) auf 64 Zeichen begrenzt. Eine entsprechende Information geht voraussichtlich im Laufe des Tages live.
