### ISSUE TITLE
API V1: SSL-Zertifikate

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#156]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Beispiel: Als Entwickler kann ich per API Domains anlegen. Aber kein (zB. LetsEncrypt) SSL-Zertifikat anlegen. 
 
**Welche Lösungsideen hast du?**
Beispiel: Das Erstellen von (zB. LetsEncrypt) SSL-Zertifikaten via API erlauben. 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**

https://developer.mittwald.de/de/reference/v1/#tag/Domains

**Comment by patrickhilker** [comment]
Das sollte gehen, ist zugegebenermaßen allerdings nicht öffentlich dokumentiert, da es bisher nur als internes Feature genutzt wird. Über die Netzwerkkonsole lassen sich die notwendigen Requests aber herausfinden.

**Comment by paul-hph** [comment]
@patrickhilker 

Kannst du einmal bestätigen, dass dies so korrekt ist? Vor allem die acricle ID: 9556.
Ich möchte vermeiden, dass ich hier massenhaft kostenpflichtige Artikel anlege. 

**endpoint:** 
`https://api.mittwald.de/v1/accounts/XXXXXX/certificates`

**payload:** 
```
{
   "article":9556,
   "domains":[
      "domain.de",
      "www.domain.de"
   ]
}

```

**response:** 

```
{
   "found":[
      "domain.de",
      "www.domain.de"
   ],
   "notFound":[
      
   ]
}
```

**Comment by patrickhilker** [comment]
Artikel 9556 heißt bei uns "Let’s Encrypt" und kostet 0,00 Euro – das passt also! 👍🏻

**Comment by patrickhilker** [comment]
Die Dokumentation ist jetzt veröffentlicht.

https://developer.mittwald.de/reference/v1/#tag/Zertifikate/operation/createOrUpgradeCertificate
