### ISSUE TITLE
basic auth über den Admin-Bereich erstellen

### ISSUE THREAD

**Issue by leonhoffmann86** [mittwald/feature-requests#159]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
ich möchte die wp-admin Seit eund Staging-Seiten mit basic auth schützen. 

**Welche Lösungsideen hast du?**
Es wäre ideal, wenn das über die Admin-GUI geht.

**Comment by patrickhilker** [comment]
Duplikat von https://github.com/mittwald/feature-requests/issues/4
