### ISSUE TITLE
SPAM Mail Filterung auch nach "Zeichen" vor dem @

### ISSUE THREAD

**Issue by The-Web-Designer** [mittwald/feature-requests#161]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Derzeit kann ich die White & Black List nur mit den folgenden Möglichkeiten anpassen:

whitelist@example.com
*@example.com
*@*.de

**Welche Lösungsideen hast du?**
Ich möchte aber zb. 

Text@*

oder

Text*@*

damit man die Filtermöglichkeiten viel feiner einstellen kann, außerdem wäre eine extra Einstellung sehr schön, ob man die Mails der White- & Blacklist "direkt löschen" möchte oder nicht, derzeit kann ich das automatische Löschen nur allgemein aktivieren, ich möchte aber z.B., dass nur Mails die der Blacklist entsprechen automatisch gelöscht werden, nicht "alle Spam"-Mails...

**Comment by The-Web-Designer** [comment]
Und bitte im Kundencenter und mStudio

**Comment by patrickhilker** [comment]
Hallo @The-Web-Designer, die Sternchen können bereits an beliebiger Stelle eingefügt werden. Falls du feststellst, dass irgendetwas nicht wie erwartet funktioniert, lass es uns gerne wissen.

**Comment by The-Web-Designer** [comment]
Ja es geht nicht, ich schreibe ein Ticket.... -> 4972220

![Screenshot 2024-05-24 103124](https://github.com/mittwald/feature-requests/assets/34239722/eae27410-7cdb-4144-a878-6aa6e009d81b)
