### ISSUE TITLE
Ticket-Mails: Deeplink zum Ticket aufnehmen

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#163]
Es ist nur eine Kleinigkeit, aber es würde in Summe viel Zeit und Klicks sparen, wenn ihr einen Link zum Ticket in eure Mails schreiben könntet. 

![LINK](https://github.com/mittwald/feature-requests/assets/3603487/d653350d-c289-474c-b607-428bec99b071)

Mit 2 Minuten Aufwand mehr vielleicht auch einfach einen schönen großen Button "Ticket aufrufen" in die Mail aufnehmen.

**Comment by benjaminkroeker** [comment]
Hallo Paul, 
vielen Dank für dein Feedback.
Das Anliegen kann ich voll und ganz nachvollziehen. 
Ich nehme das für dich mit auf und schaue, wann wir das umsetzen können.

**Comment by paul-hph** [comment]
👍 
Mir fällt ein, dass es in diesem Zusammenhang auch super wäre, wenn die angefragte URL im Falle eines nicht eingeloggten Users nach dem Login wieder aufgerufen wird. Aktuell ist es so, dass nach einem automatischen Log-Out (was bei mir häufig vorkommt) man beim Login wieder auf der Startseite landet. 

Aktuell: 

- Anfrage URL: https://login.mittwald.de/support/ticket/123456
- Redirect zum Login: https://login.mittwald.de/login
- Redirect zu Projects: https://login.mittwald.de/projects 😢 


Besser wäre:

- Anfrage URL: https://login.mittwald.de/support/ticket/123456
- Redirect zum Login mit Ziel: https://login.mittwald.de/login?redirect=https://login.mittwald.de/support/ticket/123456
- Redirect zum Ziel: https://login.mittwald.de/support/ticket/123456 😄 


Im Falle des Support-Ticket Deeplinks in den Mails würde man dann auch auf der richtigen URL landen, wenn man sich zwischendurch einloggen muss.

**Comment by benjaminkroeker** [comment]
das werden wir mit berücksichtigen 👍

**Comment by benjaminkroeker** [comment]
Hallo Paul,

gerne möchte ich dir mitteilen, dass wir deinen Vorschlag umgesetzt haben.
Ab sofort befindet sich in allen Mailnotifications zu neuen Ticketantworten im Kundencenter ein Link, der dich direkt zu deinem Ticket weiterleitet. Wenn du dich erst im Kundencenter einloggen musst, wirst du danach direkt zu deinem Ticket weitergeleitet. 
Vermutlich muss ich es nicht noch extra erwähnen, aber trotzdem der Hinweis: Seid bitte immer vorsichtig bei Mails, die Links enthalten und klickt nicht blind drauf, ohne die Herkunft der Mail zu überprüfen.

**Comment by paul-hph** [comment]
Super. Danke dafür. 🙏 🎉 

Der Deeplink funktioniert nur, weil ihr aus der Mail direkt auf /login mit angehängten Parameter `?redirect=` verlinkt, korrekt? 
(https://login.mittwald.de/login?redirect=https://login.mittwald.de/support/ticket/4912087)

**Spricht, was dagegen den Redirect Parameter immer mit anzuhängen, wenn man zb Login Formular umgeleitet wird?** 

Also wenn man folgende Seite `uneingeloggt` aufruft: 
`https://login.mittwald.de/reseller/r123456/projects/p12345` 
sollte weitergeleitet werden auf: 
`https://login.mittwald.de/login?redirect=https://login.mittwald.de/reseller/r123456/projects/p12345`



Wir haben in 1-2 internen Tools Deeplinks in euerer Backends gesetzt.
Diese funktionieren leider aktuell nur, wenn man eingeloggt ist. :-(
Das kann ich umgehen, in dem ich bei Links immer, den den Login mit Parameter verlinke. 
https://login.mittwald.de/login?redirect=https://login.mittwald.de/reseller/r123456/projects/p12345

Mir wäre es lieber, wenn ihr da einen globalen Redirect setzt. Dann würde der Benutzer auch immer da landen, wo er hinwill egal, von wo er kommt.

**Comment by benjaminkroeker** [comment]
Den Wunsch kann ich verstehen. Wir checken mal intern, welche Möglichkeiten wir da haben.
