### ISSUE TITLE
BUG: 500er Fehler bei Emojis in Support-Ticket antworten.

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#166]
Das Support-Ticket System gibt einen 500er-Fehler zurück, wenn man bestimmte Emojis in der Nachricht einer Antwort hat. 

Endpunkt: https://api.mittwald.de/v1/tickets/4982332/answers
Payload: 
```
{
   "message":"👆TEST",
   "author":{
      "name":"Paul Albrecht",
      "email":"XXX",
      "telephone":""
   },
   "customer":{
      "customernumber":"XXXX"
   },
   "files":[
      
   ]
}
```

Response: 

```
"msg": "An exception occurred while executing 'INSERT INTO `usr_web1_ticket`.`tx_mmticket_text` (`message`) VALUES(?)' with params [\"\\ud83d\\udc46TEST\"]:\n\nConversion from collation utf8mb4_0900_ai_ci into utf8mb3_general_ci impossible for parameter",
```

Wenigstens ein Hinweis geben woran es liegt, damit man weiß, wie man die Nachricht anpassen kann, damit sie durchgeht: 

![image](https://github.com/mittwald/feature-requests/assets/3603487/b4b67b2b-7830-45ce-ab13-881d41f5ab01)

**Comment by benjaminkroeker** [comment]
Hallo Paul, 
danke fürs Reporten. 
Das schauen wir uns an und geben dir Bescheid wenn es gefixt ist 🙂

**Comment by benjaminkroeker** [comment]
Hey Paul,

der Bug ist gefixt 🙂 
Liebe Grüße

**Comment by paul-hph** [comment]
🙌
