### ISSUE TITLE
BUG: Mittwald V1 API - Accounts ohne Verwaltungsfreigabe

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#171]
Der API Endpunkt: `https://api.mittwald.de/v1/customers/XXXXXX/accounts?advised=false&owned=true` 
liefert mir Accounts zurück, die nicht zur angegebenen Kundennummer gehören und für die nur eine Verwaltungsfreigabe existiert.  

Laut API Beschreibung sollten keine Accounts geliefert werden für die nur eine Verwaltungsfreigabe existiert:

https://developer.mittwald.de/de/docs/v1/reference/accounts/listAccountsByCustomer/

`advised: boolean`
`Dieser Parameter steuert, ob auch Accounts zurückgeliefert werden sollen, für die eine Verwaltungsfreigabe besteht, aber nicht zur Kundennummer {customerNumber} gehören.'`

⚠️ Könnt ihr mal prüfen, ob ihr das reproduzieren könnt und ggf. zeitnah beheben?

**Comment by patrickhilker** [comment]
Hey Paul, danke für die Info! Wir planen das mit ein.

**Comment by paul-hph** [comment]
@patrickhilker 
Gibt es da ein Zeithorizont? Wir müssen ja aufgrund der PHP Abrechnung jeden Monat alle Accounts auf alte / neue Version prüfen. Ich muss also sicher sein, dass ich von der API nur Projekte erhalten, die unsere Kundennummern zugeordnet sind.

PS: Issue gerne verschieben zu https://github.com/mittwald/developer-portal/issues

**Comment by patrickhilker** [comment]
Hallo Paul, einen genauen Zeitplan kann ich dir dafür nicht nennen.

Ich hab gerade aber den Fehler gerade einmal nachgestellt. Wenn du einfach `advised=false` weglässt, verhält sich der Endpunkt scheinbar wie von dir erwartet, d.h. es werden keine betreuten Accounts mit ausgegeben. Zusätzlich wird - zumindest mir - in jedem Account die Kundennummer angegeben, mit der ihr filtern könntet.

**Comment by paul-hph** [comment]
Hallo Patrick, 

ah ja. Danke fürs Feedback. Dann lasse ich den Parameter weg und speicher und filter noch mal nach der Kundennummer. Dann ist es nicht mehr zeitkritisch für uns. 👍

**Comment by patrickhilker** [comment]
Problem ist behoben, der Fix geht nächste Woche live. Ich schließe hier schon mal.
