### ISSUE TITLE
Mittwald Kundencenter Upload File Bug

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#174]
Könnt ihr bitte die Fehlermeldung im Frontend ausgeben?

![image](https://github.com/mittwald/feature-requests/assets/3603487/54534b29-2fdb-42d4-9c93-bc34d71bfffb)

**Comment by benjaminkroeker** [comment]
Hey Paul, 
wir kümmern uns drum 👍

**Comment by benjaminkroeker** [comment]
Hallo Paul, die Translations haben wir angepasst.
