### ISSUE TITLE
BUG: Nach Idle-Timeout Popup ohne Übersetzungen

### ISSUE THREAD

**Issue by JNBG** [mittwald/feature-requests#175]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Nachdem man einige Zeit im Hosting-Zugang inaktiv war erscheint ein Popup ohne Übersetzungen

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Screenshot zeigt das Problem. 
![Screenshot 2024-07-09 151452](https://github.com/mittwald/feature-requests/assets/16797027/80a886c1-0124-4aa0-b32e-8b29f609dc9f)
Auszug des Console-Logs (extrem gekürzt mit ..... dazwischen, die unteren Blöcke wurden ca. 100-200x wiederholt
[login.mittwald.de-1720531106329.log](https://github.com/user-attachments/files/16143793/login.mittwald.de-1720531106329.log)

**Comment by patrickhilker** [comment]
Danke fürs Reporten! Der Fehler wurde behoben, der Fix wird voraussichtlich im Laufe des Tages nach Production geschickt. Ich mache hier schon mal zu. 😊

**Comment by JNBG** [comment]
Danke für den schnellen Fix 👍

**Comment by patrickhilker** [comment]
Das Modal zeigt übrigens an, wenn ein Update für das Kundencenter verfügbar ist. Leider wird es für den gerade eingespielten Fix noch einmal ohne die passende Translation aufploppen. 😄
