### ISSUE TITLE
Autoresponder für Catch-All-Adressen

### ISSUE THREAD

**Issue by bhenselmann** [mittwald/feature-requests#177]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Wir nutzen eine neue Domain für unsere EMail-Adressen und möchten alle Mails, die an die alten Adressen gehen sowohl an einen Admin weiterleiten, als auch die Absender über die neuen Mailadressen informieren.

**Welche Lösungsideen hast du?**
Die Beschränkung, dass bei Catch-All-Adressen keine Autoresponder möglich sind, aufheben.

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Die Beschränkung kann sowieso leicht umgangen werden, indem die Catch-All-Adresse zunächst an eine andere Mailadresse weiterleitet, die dann den Autoresponder nutzt.

**Comment by jotimann** [comment]
Hallo @bhenselmann,

du hast recht, dass die Einschränkung mit einer Weiterleitung und folgenden Autoresponder umgangen werden kann.

Wir werden die Einschränkung aufgrund von Backscattering jedoch weiterhin bestehen lassen. Um unsere Reputation des Mailservers zu schützen und ausgehenden Spam zu vermeiden hilft diese extra Hürde in vielen Fällen. 

Backscattering ist das Ausnutzen von Spammern von Nicht-Zustellbarkeitsmeldungen oder anderen automatischen Rückmeldungen - in diesem Fall also ein Autoresponder. Die besondere Problematik im Zusammenhang bei Catch-All-Autorespondern ist dabei, dass Spammer oft einfach Mailadressen ausprobieren - und da sie bei einem Catch-All-Autoresponder quasi immer einen Treffer haben, wird das schnell massiv missbraucht. Dabei nehmen wir (und damit natürlich alle Kunden) aufgrund des fehlgeleiteten Autoresponders durch die gefälschte Absenderadresse schnell einen hohen Reputationsschaden.

Ich hoffe du kannst unsere Sicherheitsmaßnahme nachvollziehen und mit der Umleitung arbeiten.

Beste Grüße 
Jonas
