### ISSUE TITLE
Mailadressen-Umzug 

### ISSUE THREAD

**Issue by stpink** [mittwald/feature-requests#181]
Ich glaube, dass folgende Anregung für alle oder zumindest sehr viele Kunden und Agenturen von Euch, die selbst wiederum viele Kunden bei Euch versorgen, von großem Nutzen.

Ich habe bei Euch mehrere Server teils seit mehr als 20 Jahren.
Auf diesen Servern wurden recht viele Mailpostfächer angelegt, von denen viele Kunden heute noch die p-Nummern als Benutzername in ihren Clients verwenden.
Die Umstellung auf die Mailadresse als Benutzername stellt doch einige vor Probleme. Die Computerfreaks kommen sicher damit zurecht, andere eher nicht. Zudem befinden sich die Mailadressen der Kunden häufig auf mehreren Endgeräten, Desktop, Tablet, "Handy" oder auch in Scannern, Druckern etc.
Überall dort müsste der Kunde nach vielen Jahren der Nutzung der Mailadresse mit den p-Nummern als Benutzername nun auf allen Geräten Änderungen vornehmen.
Im Sinne der Kunden-Compliance wäre es äußerst sinnvoll, wenn man die alte p-Nummern als Alias weiterverwenden könnte.
Dies bräuchte nicht zwingend automatisch beim Umzug der Mailpostfächer von einem zum anderen Server sein, aber dass man die jeweilige p-Nummer im angelegten Mailpostfach als Benutzernamen-Alias auch gerne manuell hinzufügen könnte.

Damit wäre ein Mailumzug innerhalb der Mittwald-Server-Landschaft eine gute Idee zu mehr Kundenfreundlichkeit- und für den Kunden zu mehr Störungs- und Aufwandsvermeidung gegeben.

Wäre toll wenn ihr Euch der Sache annehmen würdet.

Viele Grüße
Stefan

**Comment by patrickhilker** [comment]
Hallo Stefan, magst du etwas Kontext liefern, in welchen Fällen die Umstellung notwendig ist? Mir ist gerade kein Fall bekannt, der das zwingend voraussetzt.
