### ISSUE TITLE
Mehr Filter für Domains-Liste integrieren

### ISSUE THREAD

**Issue by julescakecrumb** [mittwald/feature-requests#182]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Bei einem großen Datenbestand an Domains wäre es praktisch, noch weitere Filter-Optionen zu haben, um schneller Probleme entdecken zu können. Aufgrund des Nachlade-Verhaltens ist es etwas umständlich, alle Domains "mal schnell" durchzuschauen, ob es irgendwo ein Problem gibt.

**Welche Lösungsideen hast du?**
Den Filterbereich erweitern, evtl. Umbau auf Drop-Downs statt Buttons.
Praktische Filter wären noch:
- Unverifizierte Domains
- Domains mit Fehlermeldung (z. B. SSL Zertifikat konnte nicht ausgestellt werden)
- Typ (App, Weiterleitung, kein Ziel)

Die Filter könnten auch nur erscheinen, wenn es auch wirklich Treffer gibt (also z. B. nur, wenn es auch unverifizierte Domains im Bestand gibt, den Filter anbieten).

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Aktuell gibt es "nur" folgende Optionen:

![Bildschirmfoto 2024-09-03 um 08 10 30](https://github.com/user-attachments/assets/45fc980c-0b99-45eb-8d5c-ff44319f82af)

**Comment by twiesing** [comment]
@jotimann @Jan-Eimertenbrink eventuell etwas beim "Redesign" der Domain Liste mit https://mittwald.github.io/flow/03-components/structure/list.

**Comment by jotimann** [comment]
Bereits mit @Jan-Eimertenbrink geklärt. Die Filter lassen sich problemlos übernehmen. @julescakecrumb wir werden zeitnah folgende Filter hinzufügen:
- Unverifiziert
- Error
- Kein Ziel

**Comment by jotimann** [comment]
@julescakecrumb die Filter sind bereits seit ein paar Tagen Live. 
 Falls dir noch etwas auffällt öffne das Issue gerne wieder.
 Gruß Jonas
