### ISSUE TITLE
SSL-Redirect abschaltbar machen

### ISSUE THREAD

**Issue by tehplague** [mittwald/feature-requests#183]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Für Websites, die sich an chinesische Endnutzer richten und die von außerhalb Chinas betrieben werden, darf ich keine TLS-Verschlüsselung benutzen. Es scheint allerdings so, dass global ein Redirect für alle konfigurierten Domains von http:// nach https:// per HTTP 308 stattfindet. Ich erkenne das daran, dass der Redirect per HTTP 308 über HTTP/1.1 erfolgt, während später der eigentliche Website-Request per HTTP/2 beantwortet wird. Das spricht für mich dafür, dass da zwei unterschiedliche Services für verantwortlich sind.

**Welche Lösungsideen hast du?**
Der SSL-Redirect sollte abschaltbar sein, sodass Anfragen auf Port 80 auch bei der Applikation landen. Es wäre aus UX-Sicht dennoch sinnvoll, ihn standardmäßig aktiv zu belassen, um für den Average-User beim aktuellen Verhalten zu bleiben. Nichtsdestotrotz ist die Nutzung von Plain-HTTP für Websites, die in China genutzt werden sollen, ein Muss. Lösungen mit einem Proxy innerhalb Chinas sind mir zwar bekannt und werden von uns auch angeboten, erfordern aber eine örtliche ICP-Zertifizierung, die an gewisse Anforderungen geknüpft ist.

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Verhalten lässt sich einfach nachvollziehen per `curl -I http://project.tld` (Domain durch eine eigene ersetzen).

**Comment by jotimann** [comment]
Hallo @tehplague,

du kannst bereits jetzt über die API TLS deaktivieren:
https://developer.mittwald.de/docs/v2/reference/domain/ingress-update-ingress-tls/

```
{
  "acme": false
}
```

Dabei geht jedoch auch kein Let's Encrypt mehr. Falls du Let's Encrypt und https:// trotzdem nutzen möchtest, melde dich gerne einmal per Ticket bei uns. Wir können den Redirect dann im Einzelfall deaktivieren.

Ich hoffe diese beiden Optionen reichen dir.

Gruß Jonas
