### ISSUE TITLE
Speicherausgabe in JSON

### ISSUE THREAD

**Issue by maixithn** [mittwald/feature-requests#195]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
die Speicheranzeige im Studio stellt inzwischen Web,E-Mail, Datenbank und Backup Speicher dar, für das Billing wäre es toll, das auch maschienenlesbar über die API abfragen zu können

**Welche Lösungsideen hast du?**
dazu könnte man in der JSON Ausgabe mailStorageUsageInBytes, databaseStorageUsageInBytes, backupStorageUsageInBytes mit auszugeben:

[…]
  "webStorageUsageInBytes": 14213423104,
  "webStorageUsageInBytesSetAt": "2024-10-28T10:18:46.000Z"
[…]

![Image](https://github.com/user-attachments/assets/ae966e91-dc25-466a-86e8-27891c5a9e19)

**Comment by patrickhilker** [comment]
Wie du richtig schreibst, ist der Webspace in der API schon vorhanden. An den anderen Themen arbeiten wir aktuell. 😊

**Comment by patrickhilker** [comment]
Kleine Ergänzung: Über die Datenbank-Listen-Route ist es möglich, pro Datenbank den verbrauchten Speicherplatz zu laden:

- https://api.mittwald.de/v2/docs/#/Database/database-list-mysql-databases
- https://api.mittwald.de/v2/docs/#/Database/database-list-redis-databases

**Comment by patrickhilker** [comment]
Folgende Routen stehen jetzt zur Verfügung:

- [/v2/projects/{projectId}/storage-space-statistics](https://api.mittwald.de/v2/docs/#/Project/storagespace-get-project-statistics)
- [/v2/servers/{serverId}/storage-space-statistics](https://api.mittwald.de/v2/docs/#/Project/storagespace-get-server-statistics)

Aus diesen gehen jetzt sämtliche Speicherplatz-Statistiken hervor.
