### ISSUE TITLE
Externe SSL-Zertifikate

### ISSUE THREAD

**Issue by thueske** [mittwald/feature-requests#2]
**Bezieht sich dein Feature-Request auf ein zugrundeliegendes Problem? Bitte beschreibe es uns:**
Als Agentur möchte ich für Kunden mit erhöhtem Sicherheitsbedürfnis spezielle SSL-Zertifikate bereitstellen können.

**Beschreibe die Lösung(en), die du dir vorstellen könntest:**
mittwald bietet die Möglichkeit an, dass ich als Agentur SSL-Zertifikate über das mStudio hochladen kann.

**Comment by timo-poppinga** [comment]
@thueske bitte auch self singt Zertifikate zulassen Danke

**Comment by patrickhilker** [comment]
Hey @timo-poppinga, magst du kurz erklären, in welchen Fällen ihr das benötigt?

**Comment by lmrkavogt** [comment]
Das wird dann vrsl. den Erwerb von SSL-Zertifikaten über euch ersetzen? Oder sind noch einzelne "größere" Zertifikate wie SSL-Business im mStudio geplant?

**Comment by jotimann** [comment]
Moin @lmrkavogt, 
wir werden im ersten Schritt erstmal externe Zertifikate ermöglichen, sind aktuell aber dabei zu prüfen ob wir weiterhin Zertifikate über uns anbieten werden. Es steht also noch nicht 100% fest. 

Würden dir Zertifikate von mittwald im mStudio fehlen oder reicht dir die Einbindung von externen?

**Comment by lmrkavogt** [comment]
Moin :)
Ich habe es aktuell nur bei einem einzigen Projekt, also vmtl würde ich es auch extern hinbekommen.

**Comment by Nikdro** [comment]
Für uns wäre es ebenfalls sehr wichtig, kundenspezifische SSL-Zertifikate im M-Studio hochzuladen. Wir haben Kunden, die ihr eigenes Zertifikat (Wildcard-Zertifikat mit Unternehmensverifizierung per Telefon) mitbringen und dieses ebenfalls jährlich getauscht haben möchten. 

Teilweise sind die Unternehmen dazu verpflichtet, dies zu tun, weil sie zu KRITIS gehören.

Dort können wir natürlich nicht mit Let's Encrypt oder bei Mittwald gekauften "normalen" Zertifikaten ankommen.

**Comment by Jan-at-tetronik** [comment]
Für uns wäre die Möglichkeit, externe/kommerzielle Zertifikate via mStudio einzubinden, ebenfalls wichtig. Wir möchten ein Self-service-Portal für unsere externen Partner realisieren, bei dem diese über ein Web-Frontend direkt auf unsere interne Datenbank zugreifen. Hierfür ist natürlich eine möglichst hohe Verschlüsselungsstärke bzw. möglichst große Schlüssellänge erforderlich. Die Schlüssellänge des Let's-encrypt-Zertifikats ist hierfür laut unserem externen Entwicklerteam nicht ausreichend.

**Comment by jotimann** [comment]
Hier einmal ein kleines Update zum Thema:
Wir sind gerade in den letzten Umsetzungen, damit ihr externe Zertifikate automatisiert einbinden könnt. Sofern bei unseren internen Tests keine groben Probleme mehr auftreten, werden wir vermutlich in ca. 2 Wochen mit dem Feature Live gehen können. 

Ihr könnt dann pro Projekt Zertifikate hochladen und wir stellen alle zum Zertifikat passenden Domains in dem Projekt automatisch um. Dazu fügen wir unter Domains einen neuen Reiter SSL-Zertifikate hinzu: 
![image](https://github.com/user-attachments/assets/142f36c6-e1cc-4385-a727-cf94252f8662)

Sobald ein Zertifikat hochgeladen ist, werden wir alle im Zertifikat stehenden Informationen in der Übersicht darstellen:
![image](https://github.com/user-attachments/assets/35d9da6d-d0f2-4a0a-b129-3bd1ba928266)

In den Verknüpfungen seht ihr, welche Domains mit dem Zertifikat kompatibel wären und über den Status, welche das Zertifikat aktuell nutzen:
![image](https://github.com/user-attachments/assets/708626f7-e35f-487d-90f4-690b25e74bc2)

In den Domain-Details habt ihr die Option zwischen kompatiblen Zertifikaten zu wechseln oder wieder auf Let's Encrypt umzustellen:
![image](https://github.com/user-attachments/assets/9bbdba2e-9fc8-4870-a5d0-e047395fe31e)

Falls ihr Fragen oder Feedback habt, meldet euch gerne hier.
Beste Grüße aus Espelkamp
Jonas

**Comment by jotimann** [comment]
Das Feature steht euch nun wie angekündigt zur Verfügung 🚀

**Comment by vseliger** [comment]
Hallo @Nikdro, 

> Für uns wäre es ebenfalls sehr wichtig, kundenspezifische SSL-Zertifikate im M-Studio hochzuladen. Wir haben Kunden, die ihr eigenes Zertifikat (Wildcard-Zertifikat mit Unternehmensverifizierung per Telefon) mitbringen und dieses ebenfalls jährlich getauscht haben möchten. 
> Teilweise sind die Unternehmen dazu verpflichtet, dies zu tun, weil sie zu KRITIS gehören.

ist für euch auch eine C5-Testierung für eure KRITIS-Kunden relevant? Falls ja, gerne hier Rückmeldung geben: https://github.com/mittwald/feature-requests/issues/314

**Comment by Nikdro** [comment]
> Hallo [@Nikdro](https://github.com/Nikdro),
> 
> ist für euch auch eine C5-Testierung für eure KRITIS-Kunden relevant? Falls ja, gerne hier Rückmeldung geben: [#314](https://github.com/mittwald/feature-requests/issues/314)

Moin @vseliger, schön, dass du dran gedacht hast. 
Ne, bisher ist das für uns nicht relevant gewesen. 

Ich muss aber auch gestehen, dass der entsprechende Kunde damals auch nicht auf das Feature oder eine andere Lösung warten konnte und nun woanders läuft. 

Trotzdem natürlich super, wenn das möglich gemacht wird. Das hilft mit Sicherheit einigen Projekten!
