### ISSUE TITLE
Suche in Projektübersicht

### ISSUE THREAD

**Issue by steffen-hph** [mittwald/feature-requests#29]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Es gibt wohl aktuell noch keine Suche in Projektübersicht und/oder Serverübersicht?! Oder haben wir zu aktuell noch zu wenig, damit die Suche sichtbar ist?

**Welche Lösungsideen hast du?**
Eine Suche zum Durchsuchen aller Projektnamen in der Projektübersicht und vielleicht sogar auch in der Serverübersicht. Optimalerweise kann ich einige Daten des Projektes durchsuchen, also nicht nur den Namen, sondern auch Domain, Short-ID und E-Mails

**Comment by thueske** [comment]
Hi Steffen,

danke für dein Feedback! :)

Aktuell zeigen wir die Such- und Filtermöglichkeiten ab fünf vorhandenen Elementen an. Hast du bei weniger Projekten schon konkreten Bedarf nach dieser Suche?

In der aktuellen Suche kannst du immer nach dem Namen des Elements sowie der Short-ID suchen. Ganz neu in der Projektsuche ist die Eingabe der Domain, sodass dir direkt das richtige Projekt angezeigt wird.

Kannst du die Suche nach der E-Mail-Adresse vielleicht über die Eingabe der Domain in der Projektsuche bewerkstelligen oder gibt es Anwendungsfälle, bei denen du zwangsläufig die exakte E-Mail-Adresse eingeben musst?

Liebe Grüße,
Tobias

**Comment by steffen-hph** [comment]
Moin Tobias,

ah ok. Das habe ich mir fast gedacht. Wird also sobald mehr in Verwendung nicht mehr auffallen. Wenn es technisch egal ist, fänd ich das aber schongut, wenn die Suche einfach immer da ist. Einen Grund kann ich dir nicht wirklich sagen. Bauchgefühl.. ;)

> Kannst du die Suche nach der E-Mail-Adresse vielleicht über die Eingabe der Domain in der Projektsuche bewerkstelligen oder gibt es Anwendungsfälle, bei denen du zwangsläufig die exakte E-Mail-Adresse eingeben musst?

Nein, eigentlich nicht. Ich habe mit dem E-Mail Handling noch nicht gearbeitet. Vielleicht könnte bei der Suche nach einer E-Mail und dem Klick auf den Treffer direkt in die E-Mail Eigenschaften der gesuchten E-Mail geleitet werden?! Aber wie gesagt: Ich habe die UI und die Möglichkeiten der E-Mail Verwaltung noch nicht angeschaut.

**Comment by Rinxiao** [comment]
Ergänzend zu diesem Thema: Ich habe immer das Gefühl, dass ich ein paar Klicks zu viel mache, wenn ich im mStudio das Projekt wechseln möchte und es nicht gerade unter meinen letzten Zugriffen war und damit also links im Menü nicht aufgeführt wird.

Man kann zum Wechseln des Projekts aktuell zwar links auf Projekte klicken und anschließend suchen, oft klicke ich intuitiv das falsche Icon an, da das Menü auf die Icons reduziert ist, wenn man in einem anderen Projekt war.

Ich könnte mir vorstellen, dass hier ein generelles Suchfeld oben im mStudio mit Auto Suggestion und damit direkt klickbaren Ergebnissen die User Experience etwas verbessern könnte, weil man sich damit einige Klicks spart.

**Comment by jotimann** [comment]
Kleiner Zwischenstand:
Wir werden in den nächsten Tagen eine globale Suche, die von überall aus dem mStudio erreichbar ist, einführen. Im ersten Step kann dort nach Projektnamen und Domains gesucht werden und anschließend direkt in das Projekt oder zur Domain gesprungen werden. 
Diese Suche werden wir dann im laufe der Zeit immer weiter ergänzen. 

Falls ihr neben E-Mail-Adressen oder Short-IDs noch weitere Vorschläge habt, postet Sie gerne hier drunter.

**Comment by patrickhilker** [comment]
Die erste Version der Suche ist gerade live gegangen. Sie unterstützt die Suche nach Projekten und Domains. Wir freuen uns auf euer Feedback! 😊
