### ISSUE TITLE
Lock Project

### ISSUE THREAD

**Issue by maixithn** [mittwald/feature-requests#33]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich möchte versehentliches Löschen von Projekten verhindern

**Welche Lösungsideen hast du?**
ein Projekt im Status "lock" würde nur nach Aufheben der Sperre löschbar werden

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
optional könnte man ein Projekt aktiv/inaktiv stellen

**Comment by lmrkavogt** [comment]
Wäre der Löschschutz die einzige Funktion? Oder damit einhergehend dann auch die "Deaktivierung" des Projekts?

**Comment by maixithn** [comment]
Löschschutz ist mein Hauptanliegen, deaktivieren fände ich gut aber nicht wichtig …

**Comment by maixithn** [comment]
sorry: deaktivieren fände ich gut aber nicht wichtig

**Comment by patrickhilker** [comment]
Hey @maixithn, worum geht es hier genau - um ein Feature in unserer Oberfläche oder um ein Feature in der API?

**Comment by lmrkavogt** [comment]
Also zumindest das Feature deaktivieren fände ich auch für die Oberfläche wichtig. Löschschutz (brauch ich weniger) wäre auch via API/CLI denkbar

Spontan klingt die Idee von @maixithn aber auch eher nach Oberfläche? ;)

**Comment by maixithn** [comment]
ich dachte hier an eine Funktion im GUI mit der man ein Projekt sperrt gegen löschen (worst case)

**Comment by patrickhilker** [comment]
Wir haben schon jetzt beim Löschen eine zusätzliche Sicherheitsabfrage. Wünschst du dir dabei noch mehr Sicherheit? Oder gibt es noch andere Gründe dafür (z.B. mit Blick auf die verschiedenen Rechte im Projekt, ..)?

<img width="923" alt="image" src="https://github.com/mittwald/feature-requests/assets/5042280/0340e707-9e19-469f-a82d-889f6747628f">

**Comment by maixithn** [comment]
das ging schnell - danke!

**Comment by lmrkavogt** [comment]
Hmm wobei man diese Funktion sicherlich noch ausweiten könnte. Bspw: Freelancer X darf zwar alles in Apps bearbeiten, aber eben keine App löschen - ggf in anderen Szenarien genauso auf Projekt und Server-Ebene.

Oder Projekte löschen nur nach 2FA-Code?

Thema Projekte deaktivieren in ein eigene Issue? Oder ist das so oder so auf dem Schirm weil schon mal angesprochen? :)

**Comment by patrickhilker** [comment]
> Thema Projekte deaktivieren in ein eigene Issue?

Pro Thema ein Issue - sonst gehts durcheinander. :-)

Insgesamt klingt das für mich nach dem Wunsch nach einem etwas dynamischerem Rechte-/Rollenmodell - liege ich damit richtig?

**Comment by lmrkavogt** [comment]
Richtig :) soll ich einfach heute Abend/morgen zwei Issues dazu aufmachen?
- detailliertes Berechtigungskonzept
- Projekte/Apps deaktivieren

**Comment by patrickhilker** [comment]
Yes, gerne 👍🏻
