### ISSUE TITLE
API-Token je Projekt

### ISSUE THREAD

**Issue by maixithn** [mittwald/feature-requests#34]
Zum Testen oder bei Präsentationen müsste man nicht immer einen temporäres Konto anlegen und darin einen Token generieren.

Alternativ kann man sich jetzt schon einen Test Benutzer anlegen mit einem Token, der verfällt …

**Comment by patrickhilker** [comment]
Was spricht dagegen, auch in solchen Fällen ein Token deines Users zu verwenden (das dann möglicherweise natürlich auf mehr als ein Projekt zugreifen kann), bzw. wo siehst du die Vorteile eines API-Tokens pro Projekt?

**Comment by maixithn** [comment]
da spricht gar nicht gegen und ich kann auch jetzt schon einen Demo User anlegen oder wie von Dir vorgeschlagen einen Kunden Token einsetzen: zuviel Komplexität!
