### ISSUE TITLE
Support-PIN ohne Seitenwechsel

### ISSUE THREAD

**Issue by steffen-hph** [mittwald/feature-requests#35]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich hatte gestern Kontakt mit dem Support bzgl. einer mStudio Frage. Auf den Wunsch hin, die Support-PIN zu sagen musste ich jedoch aus meinem Projekt raus um in den Support-Bereich zu wechseln und die Pin erzeugen zu lassen. Darauf hin musste ich dann wieder zurück in das Projekt -> App -> Details um das Problem zu beschreiben... Umständlich

**Welche Lösungsideen hast du?**
Zum Beispiel oben rechts immer einen Button, der im **PopUp** die Support-Pin erzeugen lässt. Oder auch wenn auf weitere Buttons verzichtet werden will, in das kleine DropDown-Menü. 
Das wichtigste sehe ich darin, dass meine Seite nicht "neu läd".

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
So vielleicht? #PhotoshopPhilipp ;)
![Unbenannt-12](https://github.com/mittwald/feature-requests/assets/78363413/b6cca7b5-9c61-444f-932b-43f20f0939e9)

**Comment by patrickhilker** [comment]
Hey Steffen, super Idee - die könnte von uns sein ... 😂  Hier ein Sneak-Peak in das überarbeitete Design im Kundencenter (aber fürs mStudio könnte ich mir das ebenfalls vorstellen).

<img width="290" alt="image" src="https://github.com/mittwald/feature-requests/assets/5042280/d3ffea51-ff23-4f04-a579-5a3f5a5303ed">

**Comment by lmrkavogt** [comment]
Würde ich genauso im mStudio umsetzen, sieht super aus! 🎉

**Comment by patrickhilker** [comment]
Ich sehe gerade - das Feature haben wir schon lange umgesetzt.

<img width="200" alt="image" src="https://github.com/user-attachments/assets/ec89005a-ad1b-432e-9c08-d05e0f3194cf">
