### ISSUE TITLE
Verzeichnisschutz

### ISSUE THREAD

**Issue by thueske** [mittwald/feature-requests#4]
**Bezieht sich dein Feature-Request auf ein zugrundeliegendes Problem? Bitte beschreibe es uns:**
Ich möchte meine Entwicklungsumgebungen vor unberechtigtem Zugriff sperren.

**Beschreibe die Lösung(en), die du dir vorstellen könntest:**
Die Erstellung eines `.htaccess`-Passwortschutzes könnte automatisiert über das mStudio angeboten werden.

**Comment by maixithn** [comment]
eine Einrichtung von geschützten Verzeichnissen auf Anwenderebene fände ich auch wünschenswert, zusätzlich könnte auch htpasswd in der cli weiterhelfen (falls es schon vergleichbare Kommandos verfügbar sind bitte mitteilen)

**Comment by steffen-hph** [comment]
Da es aktuell vermutlich nicht beabsichtigt ist, dass die Passwort-Sicherheit des definierten Passworts im Kundencenter nicht korrekt geprüft wird, wollte ich das hier auch einmal anbringen, dass dieser Bug (bzw. für uns Feature) gut ist. Manchmal möchte man einfach irgendein einfaches Passwort, was man mal eben per Telefon weitersagen kann. Das schützt dann z.B. nur vor Suchmaschinen Indizierung. Also vielleicht mit lediglich einem Hinweis auf die Passwort-Sicherheit bzw. Unsicherheit?!

**Comment by lmrkavogt** [comment]
> Manchmal möchte man einfach irgendein einfaches Passwort, was man mal eben per Telefon weitersagen kann.

Ich nutz dafür eine eigene PasteBin-Installation: https://paste.lmrk.app/
Damit gibts dann auf jeden Fall keine Datenschutz-Probleme

**Comment by patrickhilker** [comment]
> zusätzlich könnte auch htpasswd in der cli weiterhelfen

@maixithn u.a. `htpasswd` steht jetzt bereit (im Cluster "Fiestel" erfolgt der Rollout nach und nach und dauert ggf. noch ein wenig - falls es dringend schneller gehen muss, hilft eine Veränderung in der Software der App).

**Comment by maixithn** [comment]
Wir freuen uns sehr über die angekündigte Lieferung … Grüße aus Fabbenstedt ;)

**Comment by holmey** [comment]
Darf ich fragen wie die Implementierung hier genau aussieht?
Wird es so sein, dass es dann eine komfortable Lösung geben wird, die .htaccess im Projekt anzupassen?
Uns würde der Verzeichnisschutz tatsächlich auf einer andern Ebene weiterhelfen. Da wir hier mit Apache arbeiten, ist die .htaccess Teil unserer Applikationen, die wir dann auch entsprechend in unsere Projekt-Repositories nutzen (z.B. Redirects, deflate, ...) und einpflegen. Ich denke es wäre praktisch den Verzeichnisschutz irgendwie vorzulagern, um so die Anwendung von der Deployment Umgebung zu trennen.
Ich gebe ein Beispiel: Setzen wir eine .htaccess auf Anwendungseben ein muss jeder Entwickler, der das Projekt lokal installiert, das Passwort kennen und eingeben.
Noch ein Beispiel: Wir haben die gleiche Anwendung als Stage und Prod App bei euch abgelegt. Die eine Umgebung benötigt Basic Auth die andere nicht.

**Comment by maixithn** [comment]
htpasswd ist jetzt verfügbar, danke! Das erleichtert die schnelle Einrichtung sehr … 

eine (mögliche) Umsetzung über die Serverkonfiguration wäre wünschenswert, sodass technische Laien das Feature verwenden können und man sich nicht ins Gehege kommt, wenn über htaccess andere Directiven eingesetzt werden wie oben beschrieben

**Comment by patrickhilker** [comment]
> [..] Wird es so sein, dass es dann eine komfortable Lösung geben wird, die .htaccess im Projekt anzupassen?
> Uns würde der Verzeichnisschutz tatsächlich auf einer andern Ebene weiterhelfen. [..]

Wie genau unsere Lösung aussieht, kann ich heute noch nicht verlässlich beantworten. Mir schwebt aber tatsächlich auch vor, dass wir irgendwie die mStudio-User automatisch integriert bekommen - möglicherweise könnte man den Zugriff dann sogar an die Rolle hängen.

Zusätzlich müssen natürlich auch andere User funktionieren - schließlich ist nicht jeder Kunde, der möglicherweise auf ein Preview-System zugreifen soll, auch automatisch im mStudio registriert.

Einfach in irgendwelchen Projekt-Dateien herumrühren möchte ich eigentlich ungern, denn, - wie du schon schreibst - das sind eure Dateien. Wir haben eh Reverse Proxys vor den Projekt-Webservern, sodass es sich möglicherweise anbieten könnte, das da zu handlen.

**Comment by maixithn** [comment]
die Integration der mStudio-User finde ich eine sehr gute Idee, die Registrierung von Projektpartnern finde ich zumutbar, wenn nicht sogar wünschenswert: dann könnte man sie auch direkt einladen ;)

**Comment by holmey** [comment]
In [Netlify](https://www.netlify.com/) hat man z.B ganz einfach die Möglichkeit pro "App" ein Passwort zu vergeben. Viel komplexer müsste es für uns gar nicht sein. Super wäre es natürlich, wenn man mehr als eine Benutzername/Passwort angeben könnte.

Eine andere Idee: Theoretisch könnten wir auch auf sehr technischer Ebene denken, denn es geht uns eher um das Herauslösen des Features Passwortschutz, aus dem Applikationscode, als um eine komfortable Möglichkeit diesen Login anzulegen.  Wenn man z.B. übergreifend Header konfigurieren könnte (eventuell aus anderen Gründen auch praktisch) wäre es auch einfach möglich Header wie folgt zu definieren: https://github.com/orgs/vercel/discussions/2920
Wo ich drüber nachdenke: Kann man in .htaccess Dateien auch auf Environment Variablen reagieren?

**Comment by pf-iservice** [comment]
In Shopware und auch bei einem anderen Provider schätze ich den Zugriff per IP-Adresse sehr. So muss ich bei Arbeits-Installationen die nicht öffentlich sein sollen nicht Login-PW eingeben. 
Shopware hat das z.B. bei der Angabe des Wartungsmodus super elegant gelöst. Neben der manuellen Eingabe von IPs wird bei Anklicken des Felds sofort die aktive IP-Adresse angezeigt und kann mit einem Klick in das Eingabefeld übernommen werden.
![23-11-2023_11-28-46](https://github.com/mittwald/feature-requests/assets/15646225/1bd00127-3b77-49f8-9360-28226d7a7f16)

**Comment by patrickhilker** [comment]
Spannender Ansatz, vielen Dank! Wo würdet ihr so eine Einstellung (IP-Beschränkung, Passwort, ...) als erstes suchen? In der App? In der Domain? Meine Tendenz geht klar zur App.

**Comment by holmey** [comment]
Wäre für mich ganz klar auf der Ebene der App und auch da ggf. nur optional, denn wenigstens in der Theorie müsste für mich eine App gar keine Verbindung nach aussen bereitstellen.

**Comment by pf-iservice** [comment]
Denke schon in der App. Zuerst Auswahl des Verzeichnisses und anschließend die Eigenschaften eingeben. Evtl. mit Select-Box on/off.

Oder, sofern es zukünftig einen File-Manager gibt, direkt bei "Eigenschaften eines Verzeichnisses". ;-)
Im Dateibaum könnte man ein geschütztes Verzeichnis optisch kennzeichnen.
Evtl. kann man so auch sFTP-Uploads von Servern externer Systeme zusätzlich absichern.

**Comment by twiesing** [comment]
Aktuell arbeiten @patrickhilker und ich an einer [Extension](https://developer.mittwald.de/docs/v2/contribution/) für das mStudio, die euch sehr einfach einen Verzeichnisschutz anlegen lässt. Das Konzept ist hierbei wie folgt:

- Ein Verzeichnisschutz kann bequem über die Benutzeroberfläche für eine App und deren Unterverzeichnisse eingerichtet werden. Er wird beispielsweise bei einer Kopie der App automatisch übernommen.
- Eine Nutzerverwaltung ermöglicht es, Benutzer zentral zu verwalten, wodurch eine Zuordnung zu mehreren Verzeichnisschutzen sowie eine einheitliche Änderung von Passwörtern für alle geschützten Verzeichnisse möglich wird.

Wir planen, zeitnah mit der Extension an den Start zu gehen und diese dann je nach Kundenfeedback (z. B. "IP-Whitelist") iterativ zu erweitern.

Hier ein aktueller Entwicklungsprototyp:
<img width="1216" alt="Image" src="https://github.com/user-attachments/assets/fdb8f049-1a7c-432c-afaa-95ee916a301a" />

**Comment by twiesing** [comment]
> Erstelle in wenigen Schritten einen Passwortschutz samt intuitiver Nutzerverwaltung für deine Apps und schütze damit sensible Bereiche wie Staging-Umgebungen vor unberechtigtem Zugriff.

@patrickhilker und ich haben im mStudio-Markt die Extension „Passwortschutz“ veröffentlicht.

Diese Features stehen euch ab sofort zur Verfügung:
1️⃣ Schützt eure Verzeichnisse mit Benutzername und Passwort.
2️⃣ Zentrale Benutzerverwaltung, z. B. für Passwortänderungen.
3️⃣ Einem Passwortschutz können beliebig viele Benutzer zugeordnet werden.
4️⃣ Kopiert ihr eine App mit aktiviertem Passwortschutz, bleibt dieser 1:1 erhalten.
5️⃣ In den kommenden Tagen: Nicht nur das Hauptverzeichnis, sondern auch Unterverzeichnisse schützen.

Wir freuen uns über euer Feedback zur neuen Extension, seien es Fragen oder spannende Feature-Ideen! 💡 Meldet euch gerne per E-Mail (die Adresse findet ihr direkt in der Extension).

**Comment by tehplague** [comment]
Wir haben die Extension gesehen. Sie betrachtet das Thema Verzeichnisschutz allerdings komplett aus Filesystem-Sicht, anstatt aus der Perspektive URL + Pfad. Dadurch ist das Tool bei Apps mit mehreren Domains nur bedingt hilfreich.
Davon abgesehen - das nur in Richtung @patrickhilker - bin ich mir auch nicht sicher, ob ich so etwas gerne mit einer 3rd-Party-Plattform managen möchte, weil ich ansonsten mit dem Extension-Entwickler einen AV-Vertrag abschließen müsste, um nen Verzeichnisschutz einzurichten.
Fände ich mit Blick auf das Container-Hosting (#1), wo der Verzeichnisschutz definitiv gebraucht wird, eher unschön.

**Comment by patrickhilker** [comment]
> Sie betrachtet das Thema Verzeichnisschutz allerdings komplett aus Filesystem-Sicht, anstatt aus der Perspektive URL + Pfad. Dadurch ist das Tool bei Apps mit mehreren Domains nur bedingt hilfreich.

Wir gucken auf den Pfad, und nicht aufs Filesystem. Schick uns gerne eine Beschreibung deines Problems, dann können wir schauen, ob wir die Domain auch mit berücksichtigen können/wollen.

 > Fände ich mit Blick auf das Container-Hosting (https://github.com/mittwald/feature-requests/issues/1), wo der Verzeichnisschutz definitiv gebraucht wird, eher unschön.

Den Zusammenhang verstehe ich leider nicht. Kannst du das erklären?

**Comment by maixithn** [comment]
ich finde es plausibel das Projekt zu schützen und nicht einzelne Apps (zumindest für unsere Bedarf) 

Allerdings würde ich mir wünschen, dass beim Zugriff opt. die Client IP abgefragt werden könnte, in Apache gesprochen:

[…|
Deny from all
Allow from 192.168.1.0/32

oder/und

[…]
Require valid-user

Es ginge prinzipiell auch beides zusammen, wenn die Client IP nicht greift, erscheint die Passwortaufforderung. 

Das Feature Client IP ist hier in irgend einam anderen Request aufgetaucht, den ich gerade leider nicht mehr finden kann.

**Comment by tehplague** [comment]
Gern. Aktuell deploye ich beispielsweise eine Applikation in eine Struktur, die (grob) so aussieht:

```
.
├── current -> releases/33
├── public -> current/public
├── releases
│   ├── 29
│   ├── 30
│   ├── 31
│   ├── 32
│   └── 33
└── shared
    ├── public
    │   ├── fileadmin    
    │   └── var
    └── web
```

Document-Root ist public/ (was nur ein Symlink ist). Darauf konfiguriert sind bspw. `https://www.example.com` und `https://www.example.org`.

**Szenario A:** Verzeichnisschutz für das Backend eines CMS unterhalb von `/admin` auf beiden Domains.
Geht m.E. nicht, weil es `/admin` nicht als physisches Verzeichnis gibt. Ich kann nur Verzeichnisse auswählen.

**Szenario B:** Verzeichnisschutz für `https://www.example.com`, während `https://www.example.org` offen bleibt.
Geht auch nicht, weil das Ganze ja aktuell nur die App als Ganzes betrachtet und keine Unterscheidung pro Domain erlaubt.

An sich wäre das ganze Thema an der von Mittwald gemanagten Ingress-Ressource im Cluster vermutlich sinnvoller aufgehangen. Da würde mich natürlich eure Meinung interessieren.

@maixithn IP-basierte Authentifizierung klingt zunächst ganz nett, aber dazu bräuchte man eigentlich zunächst IPv6-Support (#140), denn statische IPv4-Adressen werden immer seltener und je mehr sich Remote-Arbeit durchsetzt, desto weniger interessant wird die Clientadresse als Kriterium.

**Comment by tehplague** [comment]
Ach so, sorry den letzten Punkt, den du gefragt hattest, hab ich noch vergessen:

> > Fände ich mit Blick auf das Container-Hosting (https://github.com/mittwald/feature-requests/issues/1), wo der Verzeichnisschutz definitiv gebraucht wird, eher unschön.

> Den Zusammenhang verstehe ich leider nicht. Kannst du das erklären?

Wenn wir in der Lage sind, nach Belieben Software als Container zu betreiben, die ggf. keine eigene Authentifizierung mitbringen, brauchen wir ja eine Lösung, um diese mit einer Authentifizierung ausstatten zu können. Nicht jedes Tool bringt diese Fähigkeit selbst mit, sondern verlässt sich da ggf. auf den umgebenden Reverse-Proxy.

**Comment by maixithn** [comment]
sollte der Zugriff über IP gefiltert werden können und hier durch die Autoren in der Extension bereitgestellt würde, wäre das sowohl für IPv4 und später auch für IPv6 interessant. Technisch ist es ja bereits möglich über htaccess, aber leider nicht für das gesamte Projekt zentral , so dass man auch versehentlich die Anweisungen überschrieben könnte. Es geht hier ja *nicht* um die Funktion, sondern die bedienerfreundliche und fehlerfreie Oberfläche.

**Comment by maixithn** [comment]
> 
> **Szenario A:** Verzeichnisschutz für das Backend eines CMS unterhalb von `/admin` auf beiden Domains. Geht m.E. nicht, weil es `/admin` nicht als physisches Verzeichnis gibt. Ich kann nur Verzeichnisse auswählen.
> 
> **Szenario B:** Verzeichnisschutz für `https://www.example.com`, während `https://www.example.org` offen bleibt. Geht auch nicht, weil das Ganze ja aktuell nur die App als Ganzes betrachtet und keine Unterscheidung pro Domain erlaubt.
> 

so differenziert müsste es m.E. gar nicht sein, Fall A sehe ich z.B. eher in der Anwendung, der Verzeichnisschutz sollte für eine globale Zugriffskontrolle wirksam sein, schnell einzurichten und zuzverlässig sein.

**Comment by tehplague** [comment]
Alles gut, das kann man ja durchaus so sehen. Dann wäre das Ergebnis natürlich, dass das Tool für uns nicht die Wahl ist, aber damit bin ich prinzipiell als Ergebnis auch fein.
