### ISSUE TITLE
Tickets mit Rollensystem verknüpfen

### ISSUE THREAD

**Issue by twiesing** [mittwald/feature-requests#43]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich habe aktuell keine Möglichkeit alle Tickets innerhalb meiner Organisation anzusehen.

**Welche Lösungsideen hast du?**
Für die kollaborative Zusammenarbeit, v.a. in Phasen wie Urlaubszeiten, benötige ich den Zugriff auf alle Tickets innerhalb meiner Organisation.

**Comment by holmey** [comment]
Ein weiteres Szenario: Ein Projektentwickler hat auf einem Projekt (kein Organisationsmitglied) ein Ticket verfasst. Ich als Projektadministrator habe aktuell keinen Zugriff auf das Ticket.
Anders herum sollte das aber dann nicht möglich sein, weil man ja ggf. auf Freelancer auf ein projekt holt, die von bestimmter Kommunikation ausgeschlossen sein sollten.

**Comment by Nikdro** [comment]
Noch ein weiteres Szenario: Beim gemeinsamen Arbeiten an Servern/Projekten stoßen wir gemeinsam auf ein Problem, welches wir gerne mit dem Support klären möchten. Kollege B, C, usw... weiß jetzt aber gar nicht was Stand der Dinge ist und muss immer bei Kollege A nachfragen, der das Ticket erstellt hat. 

Mein Vorschlag: 
- Möglichkeit das eigene Ticket mit der ganzen Organisation zu teilen (inklusive Antwort-Recht)
- Möglichkeit das Ticket mit einzelnen Mitarbeitern der Organisation zu teilen (inklusive Antwort-Recht)
- Möglichkeit für Administratoren sich eine gesamte Ticket-Übersicht zu holen. 

Ggf. wäre zusätzlich noch eine Möglichkeit einzelne Text-Passagen als "Confidential" zu markieren hilfreich, sodass diese vielleicht für weitere Teammitglieder zensiert werden.

**Comment by benjaminkroeker** [comment]
Besten Dank fürs Teilen eurer Usecases, das hilft uns immer sehr weiter!

Kleines Status-Update zum Feature: Nachdem wir uns von einigen Seiten Feedback dazu eingeholt haben, wie unser Ticketsystem am besten erweitert werden kann, war unser UX-Team sehr fleißig und hat einige Usertests durchgeführt.
Nachdem wir die ganzen Feedbacks und Usertests ausgewertet haben, steht unser Konzept für eine erste Iteration, sodass wir in Kürze mit der Umsetzung starten können.

Ihr dürft gespannt sein 😃

**Comment by twiesing** [comment]
@benjaminkroeker magst du ein paar Screenshots teilen? 😏

**Comment by benjaminkroeker** [comment]
Hier ein kleiner Sneak Peak:

Wichtige Info: Am Konzept werden noch kleinere Optimierungen vorgenommen 😃 


![Bildschirmfoto 2023-09-18 um 11 14 47](https://github.com/mittwald/feature-requests/assets/142771434/1ec9640b-d978-462b-a226-498f6e4f7e81)
![Bildschirmfoto 2023-09-18 um 11 16 32](https://github.com/mittwald/feature-requests/assets/142771434/d0a4f62e-4804-411e-9a44-61e88a9147e1)

**Comment by LukasFritzeDev** [comment]
Mit eurem Feedback haben wir noch ein paar Optimierungen am Konzept vorgenommen und sind jetzt mit der technischen Umsetzung gestartet. Das Feature sollte also in der ersten Ausbaustufe in wenigen Wochen zur Verfügung stehen.

**Comment by benjaminkroeker** [comment]
Ab heute testen wir intern das **Ticketsystem mit mehreren Teilnehmern**.

In den nächsten Tagen werden wir ordentlich Feedbacks dazu einsammeln und dann voraussichtlich noch einmal letzte Feinheiten gerade ziehen.

Es dauert nicht mehr lang 🚀

**Comment by benjaminkroeker** [comment]
Wir sind live 🥳 

- Supportanfragen können *private* oder *shared* sein
- Mitglieder können grundsätzlich alle *shared* Conversations sehen und darin schreiben, auf deren Bezugsobjekt sie Zugriff haben
  - (*Projekt, Server, Organisation*)
- Im mStudio können Supportanfragen *private* erstellt werden
  -  auf private Supportanfragen haben keine anderen Mitglieder Zugriff
- Supportanfragen mit der Zuordnung *Allgemein* sind immer *private*

Wir sind schon richtig darauf gespannt, wie ihr das neue Feature findet und welche Vorschläge ihr dazu habt, das Feature noch besser zu gestalten.

Liebe Grüße von Benni 👋
