### ISSUE TITLE
DB Zugriff über SSH

### ISSUE THREAD

**Issue by DaRe92** [mittwald/feature-requests#44]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich möchte nach außen keinen DB Zugriff erlauben (Potenzielles Datenleck). Benötige aber über Tools (z.B. TablePlus) Zugriff auf die DB.

**Welche Lösungsideen hast du?**
Zugriff auf die DB über SSH ermöglich. Dadurch ist eine Zusätzliche Sicherung über den SSH-Key gegeben.

**Comment by patrickhilker** [comment]
Hallo Daniel, das sollte eigentlich möglich sein. Magst du einmal beschreiben, wie du vorgehen würdest/möchtest?

**Comment by DaRe92** [comment]
Ich habe es gerade noch einmal getestet. Geht nun Tatsächlich schon. Ich hatte im Februar dazu mal per Ticket nachgefragt da ging es noch nicht und war auch nicht bekannt ab wann das Verfügbar sein wird. Hatte dazu auch nirgendwo gelesen das es nun geht.

Perfekt, danke :)
