### ISSUE TITLE
Zahlungen per Lastschrift

### ISSUE THREAD

**Issue by thueske** [mittwald/feature-requests#5]
**Bezieht sich dein Feature-Request auf ein zugrundeliegendes Problem? Bitte beschreibe es uns:**
Häufig vergesse ich es meine Rechnungen zu überweisen.

**Beschreibe die Lösung(en), die du dir vorstellen könntest:**
mittwald könnte im mStudio die Zahlungsart "Lastschrift" anbieten.

**Comment by alexakruse** [comment]
Aktuell laufen interne Tests im Produktivsystem. Insofern wir keine Bugs mehr feststellen, schreiben wir Euch Ende Oktober an – falls ihr schon mal ein Ticket zum Thema Lastschrift geschrieben habt – ob ihr als Testkunde bereitsteht. 
Unser Ziel ist es, Lastschrift im November als Auswahl anbieten zu können.

**Comment by alexakruse** [comment]
Es ist November und ihr könnt Lastschrift als Zahlungsart für eure Organisation im mStudio hinterlegen! 
Tragt dazu einfach Eure Daten unter "Zahlungsmodalitäten" ein, um alle offenen Rechnungen einziehen zu lassen.
