### ISSUE TITLE
Kundencenter Facelift Facelift

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#50]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Das Facelift des Kundencenters ist gut gelungen. 
Für meinen Geschmack kann man an eigenen Stellen noch etwas nachjustieren... 

**Welche Lösungsideen hast du?**
Auf die Gefahr hin, dass ihr selbst noch mal glattzieht und ggf. mehr in Richtung des im Blogposts angekündigten [Entwurfs](https://www.mittwald.de/_Resources/Persistent/d/d/e/f/ddefdaf7570ab517002307b12b1f511bd57af36a/image%20%2819%29-800x501.png) geht, habe ich mit [Stylus]( https://add0n.com/stylus.html) einen User-Style angelegt, in dem ich die ein paar Anpassungen vorgenommen habe, die das neue Kundencenter übersichtlicher machen. (Meine Meinung!) 

https://gist.github.com/paul-hph/42814ad2ab1c07df58178bbc0da050c5

Schaut mal ob ihr davon Dinge übernehmen wollt. 🙏 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**

### Domain Liste ALT

![image](https://github.com/mittwald/feature-requests/assets/3603487/fd52efe9-178b-4d3a-8b51-c191f31cfa4a)

### Domain Liste NEU

![image](https://github.com/mittwald/feature-requests/assets/3603487/eed82aab-ff03-405d-a541-aeeeff330611)

--- 
--- 

### Formulare ALT
![FormsOld](https://github.com/mittwald/feature-requests/assets/3603487/285850f6-5683-4e26-a329-8e9970c54962)

### Formulare NEU

![FormsNew](https://github.com/mittwald/feature-requests/assets/3603487/093577b3-ebe0-4929-870b-9c5b6b59d3b9)

--- 
--- 

### Tabellen ALT

![image](https://github.com/mittwald/feature-requests/assets/3603487/d5e44237-31a8-470b-8a9f-a0c828cef8c8)

### Tabellen NEU

![image](https://github.com/mittwald/feature-requests/assets/3603487/ed51a949-0f3f-4ddb-8504-58443b7db303)

**Comment by twiesing** [comment]
Hi Paul, wir haben einige deiner Styles übernommen. Fanden wir cool, wollten wir auch. Danke für deinen Input 💪🏻

**Comment by paul-hph** [comment]
Es freut mich sehr, dass ihr das so gut annehmt und auch gleich das, was für euch passt, übernehmt. 
Könntet ihr eich noch mal die Tabellen ansehen? Die haben mal einen Rahmen, und mal nicht. 


https://github.com/mittwald/feature-requests/assets/3603487/ac6b17b4-8673-4768-bb70-1e542b9f65ea




--- 


Auch bei der Toolbar für Tabellen scheint noch sehr das alte Design durch:



https://github.com/mittwald/feature-requests/assets/3603487/2e7f1f8a-d5af-48c7-b501-8d390a75b560

**Comment by twiesing** [comment]
Hi Paul,

die Toolbar war bei uns intern noch im Code-Review, ist jetzt aber auch Live :)

**Comment by paul-hph** [comment]
<img width="1287" alt="VorlagePopup" src="https://github.com/mittwald/feature-requests/assets/3603487/3893d0d2-4d89-4176-89fb-3a91a28ec532">

👇 🙏 


<img width="1135" alt="Vorlage-PopupNeu" src="https://github.com/mittwald/feature-requests/assets/3603487/0be5bd75-5032-4a95-9275-11df19ec1568">
