### ISSUE TITLE
E-Mail-Weiterleitungsprobleme bei Weiterleitungsadressen zu externen Zielen

### ISSUE THREAD

**Issue by ThWiehe** [mittwald/feature-requests#63]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Wenn eine E-Mail Adresse als reiner Verteiler an x-beliebig andere E-Mail Adressen fungiert, lehnt der Zielserver den Mailempfang ab, wenn die eigentliche versendende E-Mail Adresse von einem anderen Mailserver stammt. Bsp.: Die weiterzuleitende E-Mail stammt von einer @gmail.com Adresse und wird durch die eingerichtete Weiterleitung an eine andere E-Mail Adresse weitergeleitet. Der mittwald Mailserver darf diese E-Mail nicht verschicken, sodass der Zielserver den Empfang der E-Mail ablehnt.

**Welche Lösungsideen hast du?**
Eine mögliche Lösung ist [SRS](https://de.wikipedia.org/wiki/Sender_Rewriting_Scheme). Besser wäre vermutlich aber eher [ARC](https://de.wikipedia.org/wiki/Authenticated_Received_Chain).

**Comment by jotimann** [comment]
ARC ist bereits seit längerem umgesetzt. Daher schließe ich dieses Issue hier mal.
