### ISSUE TITLE
Unübersichtliche Domain-Liste

### ISSUE THREAD

**Issue by vogelor** [mittwald/feature-requests#68]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Wenn ich im mstudio eine Subdomain anlegen möchte, bekomme ich eine Dropdown mit SÄMTLICHEN Domains, die ich habe. Diese Liste ist ziemlich groß (unübersichtlich) und auch noch "komisch" sortiert. Ich tue mich jedes mal schwerer, die richtige "Haupt-Domain" auszuwählen.

**Welche Lösungsideen hast du?**
Sämtliche Domains, die INNERHALB DES SELBEN Projekts existieren sollen in der Liste OBEN stehen. Dann muss ich nicht so suchen...

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Nein

**Comment by jotimann** [comment]
Hallo @vogelor,
die Lösung nur Domains aus dem selben Projekt anzuzeigen, hatten wir zuvor. 
Dabei sind Kunden auf das Problem gestoßen, wenn die Hauptdomain z.B. "preview.de" in einem Account liegt und man nun für jeden Unterkunden eine Subdomain zur Vorschau erstellt, beispielsweise FirmaA.preview.de, konnte man diese nicht im anderen Account anlegen.

Du hast beim Anlegen der Subdomain im "Domain wählen"-Input-Field die Möglichkeit bereits einen Teil der Domain einzugeben, um das Drop-Down zu filtern. Reicht dir die Eingabe nicht um die passende Domain zu finden?

Bzgl. der "komischen" Sortierung prüfe ich das ganze nochmal. Was würdest du hier erwarten? (Nach Domain, Alphabetisch...)

**Comment by vogelor** [comment]
Ich meinte nicht NUR die des Projektes, ich meine, die des Projektes OBEN beim Sortieren, Warum ihr das gemacht habt ist mir klar ;-)

Ich würde erwarten, alphabetisch

**Comment by jotimann** [comment]
Hallo @vogelor,
wir haben die Liste wie folgt angepasst:
1. Zuerst werden alle Domains aus dem Projekt in dem du dich befindest alphabetisch angezeigt. 
2. Anschließend alle weiteren Domains auf die du Zugriff hast (alphabetisch)
