### ISSUE TITLE
.com-Domains bestellbar machen

### ISSUE THREAD

**Issue by thueske** [mittwald/feature-requests#7]
**Bezieht sich dein Feature-Request auf ein zugrundeliegendes Problem? Bitte beschreibe es uns:**
Für meine Kunden benötige ich die Möglichkeit `.com`-Domains zu bestellen.

**Beschreibe die Lösung(en), die du dir vorstellen könntest:**
mittwald bietet im mStudio die Möglichkeit `.com`-Domains zu bestellen.

**Comment by jotimann** [comment]
Ab sofort können .COM-Domains im mStudio registriert werden. Um diese Funktion frühstmöglich bereitzustellen, gibt es noch 2 Einschränkungen:
- Umzüge von bestehenden Domains sind noch nicht möglich
- Bei den Kontaktdaten können Name und E-Mail noch nicht bearbeitet werden
