### ISSUE TITLE
Cronjob Alternative supervisor

### ISSUE THREAD

**Issue by aneufeld23** [mittwald/feature-requests#79]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Bei Symfony-Anwendungen werden viele Jobs über die MessageQueue abgearbeitet, diese werden meistens über Cronjobs angestoßen. Allerdings können Cronjobs nur max. 1x pro Minute gestartet werden. Bricht ein Cronjob ab, wird auf die nächste Ausführung gewartet.

**Welche Lösungsideen hast du?**
Die Möglichkeit Cronjobs als Supervisor oder über Systemd laufen zu lassen. 

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Symfony über [supervisor](https://symfony.com/doc/current/messenger.html#supervisor-configuration) und [systemd](https://symfony.com/doc/current/messenger.html#systemd-configuration)

**Comment by patrickhilker** [comment]
Duplikat von https://github.com/mittwald/feature-requests/issues/76
