### ISSUE TITLE
Zwei-Faktor-Authentifizierung

### ISSUE THREAD

**Issue by thueske** [mittwald/feature-requests#8]
**Bezieht sich dein Feature-Request auf ein zugrundeliegendes Problem? Bitte beschreibe es uns:**
Zum Schutz vor Pishing- und Hackerangriffen möchte ich meine Zugänge zum mittwald Kundencenter bestmöglich absichern.

**Beschreibe die Lösung(en), die du dir vorstellen könntest:**
Anbieten einer Zwei-Faktor-Authentifizierung, sodass selbst ein möglicher Verlust von Zugangsdaten kein Zugriff auf sensible Daten zulässt.

**Zusätzliche Informationen (wie z.B. Screenshots):**
Umsetzung mit TOTP-Token (vgl. Google Authenticator).

**Comment by twiesing** [comment]
Wir werden das Feature am Montag (04.09. ab 19 Uhr) ins Produktivsystem deployen.

**Comment by patrickhilker** [comment]
2FA steht seit gestern Abend im Kundencenter zur Verfügung.
