### ISSUE TITLE
Backend-Performance einer Website testen

### ISSUE THREAD

**Issue by patrickhilker** [mittwald/feature-requests#80]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Als Entwickler habe ich festgestellt, dass eine meiner Seiten nicht in der gewünschten Geschwindigkeit geladen wird. Da mein Frontend schnell genug ist (das habe ich durch die [mittwald Performance-Messung](https://www.mittwald.de/blog/hosting/performance-kpis-im-mstudio-so-optimierst-du-die-kennzahlen) festgestellt) muss es am Backend liegen. Ich muss nun also prüfen, warum mein Backend zu langsam ist.

**Welche Lösungsideen hast du?**
mittwald sollte mir ein Tool bereitstellen, mit dem ich in der Lage bin, genau herauszufinden, welche Aspekte meines Backends die Performance-Probleme verursachen. mittwald erstellt mir eine detaillierte Analyse. Wenn ich noch tiefer in das Thema einsteigen möchte, kann ich von mittwald auch die Roh-Messwerte erhalten.

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
- [strace](https://en.wikipedia.org/wiki/Strace)

**Comment by fe-hicking** [comment]
Cool wäre sowas wie:
- schicke nen HTTP request an eine API von mittwald, mit auth für welche seite ich profiling aktivieren möchte
- die gibt mir nen cookie wieder, startet strace auf dem php prozess, der zu "meinem" projekt gehört
- den cookie baue ich jetzt für die backend http requests ein, die ich von euch profilen lassen will
- am ende deaktivier ich mit nem Schritt wie dem ersten das tracing wieder (oder automatisch nach X Minuten)
- die auswertung/graphen gruppiert nach queries/fstat/etc schickt ihr mir danach in euer backend UI oder per Mail oder speichert es im Projekr-webspace
- wenn mehrere requests auf dieselbe uri stattfanden wird ein mittelwert der calls erhoben

(Nur Gedanken, um das Ticket zu füllen. Toller T3CRR Vortrag, war hervorragend zu folgen und fachlich/sachlich spot-on 👍)

**Comment by patrickhilker** [comment]
> (Nur Gedanken, um das Ticket zu füllen. Toller T3CRR Vortrag, war hervorragend zu folgen und fachlich/sachlich spot-on 👍)

Wenn du gleich noch einen Moment Zeit hast, könnte ich eine kleine Demo zeigen. Grüße aus der letzten Reihe. ✌🏼

**Comment by patrickhilker** [comment]
Kleiner Sneak Peak in die Entwicklung. Wir werden im ersten Schritt ermöglichen, einfache GET-HTTP-Requests zu messen. Perspektivisch werden wir dann nach Bedarf weitere Request-Arten und Payload ermöglichen. Natürlich ist das auch vollständig per API bedienbar.

Damit werden wir dann voraussichtlich noch dieses Jahr live gehen.

<img width="1302" alt="image" src="https://github.com/mittwald/feature-requests/assets/5042280/3cdaf914-95ed-46a0-8c33-1c4475ad2a52">

**Comment by garvinhicking** [comment]
Wow, hervorragend, das ist ja schon ziemlich vorangeschritten und cool. Schade, dass ich die Demo nicht mehr wahrnehmen konnte, aber das ist wirklich eine schöne Übersicht. Wenn wir (Faktor E GmbH) das mal in "unseren" Projekten testen dürfen/können/sollen, ich würd mich freuen :-)

**Comment by patrickhilker** [comment]
> Wenn wir (Faktor E GmbH) das mal in "unseren" Projekten testen dürfen/können/sollen, ich würd mich freuen :-)

Klar - ich komme auf euch zu, wenn wir so weit sind. Falls es noch weitere Interessenten gibt, meldet euch gerne hier im Issue.

**Comment by bugskarl** [comment]
@patrickhilker schaut cool aus. glaube aber, dass dieses feature nur für allgemeine performance tendenzen hergenommen werden kann.
um genauere analysen von unseren projekten machen zu können würden wir server seitig packages brauchen um: https://blackfire.io/, https://www.datadoghq.com/, https://www.dynatrace.com/, https://docs.sentry.io/product/performance/, ... laufen lassen zu können.
wir haben z.b. sentry im einsatz - wenn am server das php_excimer modul zur verfügung stünde könnten wir hier selber wunderbare performance analysen erstellen von unserer applikation.

**Comment by patrickhilker** [comment]
Das Feature wird morgen live gehen. Wer jetzt schon spicken möchte, hier entlang: https://studio.mittwald.de/?featureFlags=WyJzaG93U2VydmVyUGVyZm9ybWFuY2UiXQ%3D%3D (ein paar kleine Fehler/Unschönheiten verschwinden morgen noch mit dem Livegang).

Das Feature findet sich im Projekt unter "Performance" -> "TTFB-Analyse". Bin gespannt aufs Feedback.

@bugskarl bzgl. `php_excimer` und weiterer Integrationen mache ich mich nochmal schlau, was wir da zeitnah machen können.

**Comment by patrickhilker** [comment]
> @bugskarl bzgl. php_excimer und weiterer Integrationen mache ich mich nochmal schlau, was wir da zeitnah machen können.

In der aktuellen PHP 8.3.1 (8.3.2 kommt zeitnah) sollte die Extension jetzt zur Verfügung stehen. Du kannst sie über die `php.ini` aktivieren. Ältere Versionen erhalten die Extension demnächst ebenfalls.

Lass mich gerne wissen, ob alles wie erwartet funktioniert.
