### ISSUE TITLE
Empfang von E-Mails zu spezifischen Adressen blockieren bei aktiver Catch-All

### ISSUE THREAD

**Issue by fabianhueske** [mittwald/feature-requests#89]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Wenn ich alle E-Mails zu einer Adresse mit Hilfe der Catch-All Funktion "catchen" lasse, habe ich zurzeit nicht die Möglichkeit spezifische Empfänger-Adressen zu blockieren.
Wir bemerken gerade, dass wir vermehrt Spam bekommen zu einer automatisch generierten Adresse die vermutlich durch einen Bot irgendwo aufgeschnappt wurde. In dem Fall wäre es sehr hilfreich alle E-Mails die an `nervige.emails@unsere-domain.de` gesendet werden automatisch zu löschen oder in den Spam-Ordner zu schieben.

**Welche Lösungsideen hast du?**
Man könnte vielleicht eine "blockierte Empfänger-Adressen" Funktion an der Catch-All-Option hinzufügen, zu der man dann die nicht erwünschten Adressen hinzufügt und das gewünschte Verhalten mit E-Mails die an diese Adresse geschickt werden konfiguriert.

Alternativ würde es vielleicht auch bei den Spam-Schutz-Einstellungen Platz finden, da es ja weniger mit der Catch-All zu tun hat und mehr mit dem Vermeiden von Spam. Dort wäre dann vielleicht auch direkt die Kombi mit einer "blockierte Sender-Adressen" Funktion sinnvoll? 🤷‍♂️ 

Aber gebt nicht so viel auf meine Ideen, ihr kennt euer Produkt und eure Möglichkeiten besser 😄

**Comment by jotimann** [comment]
Hallo @fabianhueske,

ich würde das Thema einmal mit [diesem](https://github.com/mittwald/feature-requests/issues/51) verbinden. Dabei geht es um Filtermöglichkeiten für deine E-Mail-Adresse. 
In deinem Beispiel: "Empfänger ist `nervige.emails@unsere-domain.de` -> Papierkorb"

Du kannst als Workaround aktuell die Adresse `nervige.emails@unsere-domain.de` im mStudio anlegen und diese ins "Nichts" Weiterleiten. Angelegte Adressen sind immer bevorzugt gegenüber der Catch-All-Adresse. So bekommst du diese E-Mails nicht mehr.

Die Lösung ohne Workaround wären dann die Filtermöglichkeiten.

Ich schließe das ganze hier erstmal. Sollte Workaround und Filtermöglichkeiten deiner Meinung nach nicht ausreichen melde dich gerne nochmal.

Gruß Jonas
