### ISSUE TITLE
Facelift

### ISSUE THREAD

**Issue by thueske** [mittwald/feature-requests#9]
**Bezieht sich dein Feature-Request auf ein zugrundeliegendes Problem? Bitte beschreibe es uns:**
Das Kundencenter ist an einigen Stellen langsam und bietet keinen modernen Look.

**Beschreibe die Lösung(en), die du dir vorstellen könntest:**
Optimierung der Gesamt-Performance inklusive Redesign von Menü, Ticketsystem und DNS-Editor.

**Zusätzliche Informationen (wie z.B. Screenshots):**
[Blog-Artikel zum Facelift](https://www.mittwald.de/blog/hosting/facelift-fuer-das-kundencenter)

**Comment by twiesing** [comment]
Wir werden die Änderungen am Montag (04.09. ab 19 Uhr) ins Produktivsystem deployen.

**Comment by patrickhilker** [comment]
Der neue Look des Kundencenters steht seit gestern Abend zur Verfügung. 😊

**Comment by paul-hph** [comment]
Wäre es möglich das Issue wieder aufzumachen. Ich finde, da ist noch viel Raum für Feedback..

**Comment by patrickhilker** [comment]
> Wäre es möglich das Issue wieder aufzumachen. Ich finde, da ist noch viel Raum für Feedback..

Nutz für neue Features gern neue Issues - oder du fasst uns das Feedback per Ticket zusammen. Wie es für dich einfacher ist. :-)

**Comment by paul-hph** [comment]
https://github.com/mittwald/feature-requests/issues/50
