### ISSUE TITLE
Catch-All für Weiterleitungsadresse

### ISSUE THREAD

**Issue by twiesing** [mittwald/feature-requests#94]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Ich möchte alle eingehenden E-Mails (Catch-All) an eine externe E-Mail-Adresse weiterleiten.

**Welche Lösungsideen hast du?**
Catch-All für Weiterleitungsadressen erlauben.

**Comment by jotimann** [comment]
Im mStudio kann nun Catch-All für eine Weiterleitungsadresse gesetzt werden 🚀
