### ISSUE TITLE
rsync

### ISSUE THREAD

**Issue by paul-hph** [mittwald/feature-requests#98]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Beispiel: Als Entwickler einer Agentur muss ich häufiger Projekte migrieren. Aktuell muss für den Transfer der Dateien ein Archiv erstellt und übertragen werden. Dafür muss genügend Speicherplatz auf dem Source System zur Verfügung stehen, was nicht immer der Fall ist. 

**Welche Lösungsideen hast du?**
Bitte schafft die Option `rsync` auf den mStudio Servern zu installieren. Damit kann man schnell und effizient Dateien übertragen.

**Comment by patrickhilker** [comment]
Hey Paul, `rsync` ist "schon immer" standardmäßig installiert - was genau fehlt dir?

**Comment by paul-hph** [comment]
🤷‍♂️ Stimmt.  Hatte `command not found`erhalten.   Muss mich vertippt oder sonst wo gewesen sein...
