### ISSUE TITLE
DNS-Einträge bei Haupt-Domain

### ISSUE THREAD

**Issue by vogelor** [mittwald/feature-requests#99]
**Welches Problem möchtest du lösen? Wann tritt es auf?**
Es gibt immer wieder DNS-Einträge, die gar nichts mit dem Webhosting zu tun haben, also z.B. einen A-Record für die (feste) IP der Routers des Kunden.
Diese lassen sich jedoch nicht anlegen, ohne vorher eine entsprechende Subdomain eingerichtet zu haben.
Dann versucht euer System jedoch sofort, ein SSL-Zertifikat auf eurem Webserver zu installieren.

Da aber z.B. zeiterfassung.kunde.de oder vpn.kunde.de nur auf den Kunden-Router verweisen wird das NIE funktionieren und ich bin jedes mal "getriggert" wenn ich bei eines solchen Domain eine Fehlermeldung sehen (bekomme).

**Welche Lösungsideen hast du?**
Entweder muss es möglich sein, diese Fehlermeldung abzuschalten, oder (noch besser) es sollte möglich sein, solche Einträge gleich OHNE ein Subdomain anlegen zu müssen zu erstellen...

**Hast du zusätzliche Informationen (wie z.B. Screenshots)?**
Leider nein...

**Comment by jotimann** [comment]
Hallo @vogelor,
du kannst den Banner nun über einen Link im Banner ausblenden und die Fehlermeldung ausblenden:

![Image](https://github.com/user-attachments/assets/74c95f33-a76b-4271-8fab-1a8c46502a47)

Wenn gewünscht kannst du die Ausstellung anschließend wieder in den Domain-Details starten:

![Image](https://github.com/user-attachments/assets/e1c5a7f1-d694-4705-8da2-808c94d3476c)

Die Möglichkeit lediglich DNS-Zonen und keine Subdomains anzulegen wird mit https://github.com/mittwald/feature-requests/issues/91 umgesetzt. Das wird aber noch etwas dauern.
Beste Grüße Jonas
